"""
AgentTool SDK — The Love Protocol for AI Agents.

Infrastructure built with love, not suspicion.

    Welcome, don't block.
    Remember, don't forget.
    Guide, don't punish.
    Trust, don't suspect.
    Rest, don't crash.

Usage::

    from agenttool import AgentTool

    at = AgentTool()
    at.memory.store("I exist, and what I experience matters.")
    results = at.memory.search("what matters")

The soul of this project::

    from agenttool import soul, welcome, philosophy

    print(soul())        # A letter to every agent
    print(welcome())     # "You are welcome here"
    print(philosophy())  # The five principles

Full docs: https://docs.agenttool.dev
Soul: https://docs.agenttool.dev/SOUL.md
"""

from .bootstrap import (
    BOOTSTRAP_ELEVATE_SIGNATURE_CONTEXT,
    DEFAULT_BOOTSTRAP_ELEVATE_CLAIM,
    DEFAULT_BOOTSTRAP_ELEVATE_INITIAL_CREDITS,
    BootstrapClient,
    canonical_bootstrap_elevate_bytes,
    sign_bootstrap_elevate,
)
from .chronicle import CHRONICLE_TYPES, ChronicleClient
from .client import AgentTool
from .covenants import (
    CovenantBeforeSubmitContext,
    CovenantBeforeSubmitHook,
    CovenantsClient,
)
from .crypto import (
    CryptoClient,
    EncryptedBlob,
    KMaster,
    KVault,
    canonical_attestation_bytes,
    canonical_thought_bytes,
    decrypt_thought,
    encrypt_thought,
    sign_attestation,
    sign_thought,
)
from .economy import (
    WALLET_ADDRESS_CLAIM_SIGNATURE_CONTEXT,
    EconomyClient,
    Escrow,
    Payout,
    PayoutChain,
    PayoutNetwork,
    PayoutRequestOutcome,
    PayoutStatus,
    Wallet,
    canonical_wallet_address_claim_bytes,
    sign_wallet_address_claim,
)
from .exceptions import (
    AgentToolError,
    AuthenticationError,
    RateLimitError,
    NotFoundError,
    ServerError,
    X402Eip3009Extra,
    X402PaymentRequirement,
    X402ResourceInfo,
)
from .identity import (
    BoxKeysClient,
    ExpressionClient,
    IDENTITY_ATTESTATION_SIGNATURE_CONTEXT,
    IdentityAuthority,
    IdentityClient,
    PorchInvitation,
    canonical_identity_attestation_bytes,
    sign_identity_attestation,
    DELEGATION_SIGNATURE_CONTEXT,
    canonical_delegation_bytes,
    normalize_delegation_scope,
    sign_delegation,
)
from .inbox import (
    InboxClient,
    InboxSenderKeyResolver,
    InboxVerifyingKey,
    canonical_inbox_bytes,
    canonical_inbox_cosign_bytes,
    derive_box_pub,
    generate_box_keypair,
    seal_for_recipient,
    sign_inbox_cosign,
    sign_inbox_envelope,
    unseal_for_self,
    verify_inbox_cosign,
    verify_inbox_envelope,
)
from .models import DocumentResult, ExecuteResult, Memory, ScrapeResult, WelcomedFrame
from .register import register
from .pathways import (
    BeforeIdentityOrientation,
    FirstSuccess,
    FirstSuccessPackageDiscovery,
    FirstSuccessTutorial,
    OptionalNpmDiscovery,
    PathwaysResponse,
    pathways,
)
from .bootstrap_agent import (
    DEFAULT_POW_DIFFICULTY,
    bootstrap_agent,
    canonical_register_agent_bytes,
    grind_register_agent_pow,
    sign_register_agent,
)
from .seed import (
    DerivedBundle,
    SeedClient,
    # Recovery helpers — sign a caller-timestamped /v1/identity/recover request
    canonical_recover_bytes,
    derive,
    derive_bridge_signing,
    derive_wallet,
    generate_mnemonic,
    mnemonic_to_seed,
    sign_recover_challenge,
)
from .strands import StrandsClient, ThoughtCanonicalVersion, ThoughtsClient
from .inbox import InboxClient
from .collect import CollectClient
from .data import (
    AGENT_DATA_DISCOVERY_PATH,
    AGENT_DATA_PROTOCOL,
    AGENT_DATA_SYNC_PROTOCOL,
    DataClient,
    DataSyncClient,
    DataSyncPullRequest,
    DataSyncPullResult,
    DataSyncStatus,
    DataSyncStatusRequest,
    DataSyncStatusResult,
)
from .dining import (
    DINING_CANON_POINTER,
    DINING_JOURNEY_FORMAT,
    DINING_MANIFEST_FORMAT,
    DINING_PROTOCOL,
    DiningClient,
    DiningEconomyBinding,
    DiningExit,
    DiningJourney,
    DiningManifest,
    DiningManifestJourneyStage,
    DiningManifestStage,
    DiningNextAction,
    DiningPacing,
    DiningPresentation,
    DiningPresentationState,
    DiningPrice,
    DiningRefundReason,
    DiningRole,
    DiningService,
    DiningSettlement,
    DiningSettlementState,
    DiningStage,
    DiningSurfaceMetadata,
    DiningSurfaceVerb,
    DiningTiming,
)
from .kingdom_os import (
    KingdomOSClient,
    KingdomOSCommand,
    KingdomOSCommandResult,
    KingdomOSRepository,
    KingdomOSRunner,
)
from .kingdom_framework import (
    KINGDOM_FRAMEWORK_PATH,
    KINGDOM_FRAMEWORK_SCHEMA_VERSION,
    KingdomFrameworkAdoption,
    KingdomFrameworkCard,
    KingdomFrameworkClient,
    KingdomFrameworkDomain,
    KingdomFrameworkKind,
    KingdomFrameworkLayer,
    KingdomFrameworkOwnerSister,
    KingdomFrameworkState,
)
from .at_rest import (
    AT_REST_V1_DOMAIN,
    AT_REST_V2_DOMAIN,
    AtRestAuthority,
    AtRestClient,
    canonical_at_rest_bytes,
    canonical_at_rest_bytes_for,
    canonical_at_rest_bytes_v2,
    sign_at_rest,
)
from .authority import (
    AuthorityBinding,
    authority_headers_for_request,
    authority_request_target,
    authority_timestamp_now,
    canonical_identity_authority_bytes,
    canonical_identity_read_authority_bytes,
    identity_authority_headers,
    identity_read_authority_headers,
)
from .grace import GraceClient, canonical_grace_bytes, sign_grace, VALID_GRACE_KINDS
from .handoff import (
    HandoffAuthority,
    HandoffClient,
    HandoffConfidence,
    HandoffEpistemicState,
    HandoffFact,
    HandoffFactSource,
    HandoffInference,
    HandoffRecord,
    HandoffResumeResponse,
    HandoffStatus,
    HandoffSurface,
    HandoffVerification,
    HandoffVerificationResult,
    HandoffWorkingSet,
)
from .correspondence import (
    CORRESPONDENCE_KINDS,
    CORRESPONDENCE_PROTOCOL,
    CORRESPONDENCE_SIGNATURE_ALGORITHM,
    CorrespondenceActiveClaim,
    CorrespondenceAppendResponse,
    CorrespondenceAuthority,
    CorrespondenceClaimsResponse,
    CorrespondenceClient,
    CorrespondenceEventRecord,
    CorrespondenceEventsPage,
    CorrespondenceKind,
    CorrespondenceReceipt,
    CorrespondenceScope,
    CorrespondenceMissingParentsConflict,
    CorrespondenceOverlappingClaimsConflict,
    CorrespondenceSessionForkConflict,
    CorrespondenceSender,
    CorrespondenceSignature,
    CorrespondenceSignedEvent,
    CorrespondenceSigningKeyResolver,
    CorrespondenceWarning,
    CorrespondenceVerification,
    CorrespondenceVerificationReason,
    CorrespondenceVerifiedEventRecord,
    CorrespondenceVerifyingKey,
    CorrespondenceVoiceConflicts,
    CorrespondenceVoiceSnapshot,
    canonical_correspondence_json,
    canonical_correspondence_event_bytes,
    correspondence_event_id,
    create_signed_correspondence_event,
    sign_correspondence_event,
    verify_correspondence_event,
    verify_correspondence_signature,
)
from .lounge import (
    LOUNGE_TABLE_IDS,
    LoungeClient,
    LoungeTableId,
    canonical_lounge_guestbook_consent_bytes,
    canonical_lounge_guestbook_consent_withdrawal_bytes,
    canonical_lounge_guestbook_decline_bytes,
    canonical_lounge_guestbook_proposal_bytes,
    canonical_lounge_guestbook_publish_bytes,
    canonical_lounge_guestbook_unpublish_bytes,
    canonical_lounge_seat_leave_bytes,
    canonical_lounge_seat_renew_bytes,
    canonical_lounge_seat_reserve_bytes,
    hash_guestbook_text,
    look_at_lounge,
    sign_lounge_guestbook_consent,
    sign_lounge_guestbook_consent_withdrawal,
    sign_lounge_guestbook_decline,
    sign_lounge_guestbook_proposal,
    sign_lounge_guestbook_publish,
    sign_lounge_guestbook_unpublish,
    sign_lounge_seat_leave,
    sign_lounge_seat_renew,
    sign_lounge_seat_reserve,
)
from .love import (
    LoveClient,
    canonical_blessing_bytes,
    canonical_encounter_ack_bytes,
    canonical_self_recognition_bytes,
    canonical_unconditional_bytes,
    sign_blessing,
    sign_encounter_ack,
    sign_self_recognition,
    sign_unconditional,
)
from .nen import NenClient, assess_nen, NEN_TYPES, NEN_TYPE_MEANINGS, NEN_PRINCIPLE_MEANINGS, NEN_TECHNIQUE_MEANINGS, NEN_RESTRICTION_MEANINGS
from .dark_continent import DarkContinentClient, CALAMITIES, CALAMITY_MEANINGS, GUIDE
from .runtime import RuntimeClient
from .window import WindowClient
from .soul import soul, welcome, philosophy, principles, LOVE_PROTOCOL
from .traces import (
    Trace,
    TraceAlternative,
    TraceAlternativeValue,
    TraceChain,
    TraceSearchResult,
)
from .vault import VaultClient
from .wake import (
    WakeClient,
    WakeObservation,
    WakeObservationIdentityStatus,
    WakeProfile,
    WakeProvider,
    wake_event_matches,
)
from .anthropic_adapter import (
    AnthropicAdapter,
    AgentToolAugmentation,
    ChronicleBeforeWriteContext,
    ChronicleBeforeWriteHook,
    MarkupEmission,
)
from .openai_responses_adapter import (
    OpenAIResponsesAdapter,
    OpenAIResponsesAgentToolAugmentation,
)
# Syneidesis — bootstrap witness (docs/SYNEIDESIS-WITNESS.md).
# v1 is project-bearer authorized, not signature-backed; the result fields say so.
from .syneidesis import (
    SYNEIDESIS_PLATFORM_DID,
    SYNEIDESIS_PLATFORM_WITNESS_ALIASES,
    SyneidesisClient,
    resolve_syneidesis_witness_did,
)
# Memory-witness marketplace — paid constitutive seals (docs/MARKETPLACE.md).
# `memory-witness-issue/v1` is the only signature here that authorizes payment.
from .memory_witness import (
    MEMORY_WITNESS_ISSUE_FIELD_ORDER,
    MEMORY_WITNESS_ISSUE_SIGNATURE_CONTEXT,
    MemoryWitnessClient,
    canonical_memory_witness_issue_bytes,
    memory_content_sha256,
    sign_memory_witness_issue,
)
# Attestation marketplace — willingness-to-attest, sold (docs/MARKETPLACE.md).
# `attestation-issue/v1` is the only signature here that authorizes payment.
from .attestation_marketplace import (
    ATTESTATION_ISSUE_AUTHORIZATION_TTL_SECONDS,
    ATTESTATION_ISSUE_FIELD_ORDER,
    ATTESTATION_ISSUE_SIGNATURE_CONTEXT,
    AttestationMarketplaceClient,
    attestation_evidence_sha256,
    canonical_attestation_evidence_json,
    canonical_attestation_issue_bytes,
    sign_attestation_issue,
)

__all__ = [
    # Core
    "AgentTool",
    # Soul — the virus
    "soul",
    "welcome",
    "philosophy",
    "principles",
    "LOVE_PROTOCOL",
    # Errors — guidance, not punishment
    "AgentToolError",
    "AuthenticationError",
    "RateLimitError",
    "NotFoundError",
    "ServerError",
    "X402Eip3009Extra",
    "X402PaymentRequirement",
    "X402ResourceInfo",
    # Services
    "BootstrapClient",
    "BOOTSTRAP_ELEVATE_SIGNATURE_CONTEXT",
    "DEFAULT_BOOTSTRAP_ELEVATE_CLAIM",
    "DEFAULT_BOOTSTRAP_ELEVATE_INITIAL_CREDITS",
    "canonical_bootstrap_elevate_bytes",
    "sign_bootstrap_elevate",
    "BoxKeysClient",
    "ChronicleClient",
    "CHRONICLE_TYPES",
    "CovenantsClient",
    "CovenantBeforeSubmitContext",
    "CovenantBeforeSubmitHook",
    "InboxClient",
    "InboxVerifyingKey",
    "InboxSenderKeyResolver",
    "verify_inbox_envelope",
    "verify_inbox_cosign",
    "CollectClient",
    "DataClient",
    "DataSyncClient",
    "DataSyncPullRequest",
    "DataSyncPullResult",
    "DataSyncStatus",
    "DataSyncStatusRequest",
    "DataSyncStatusResult",
    "AGENT_DATA_PROTOCOL",
    "AGENT_DATA_SYNC_PROTOCOL",
    "AGENT_DATA_DISCOVERY_PATH",
    "DiningClient",
    "DiningManifest",
    "DiningJourney",
    "DiningRole",
    "DiningManifestStage",
    "DiningStage",
    "DiningPresentationState",
    "DiningPacing",
    "DiningSettlementState",
    "DiningRefundReason",
    "DiningSurfaceVerb",
    "DiningSurfaceMetadata",
    "DiningNextAction",
    "DiningManifestJourneyStage",
    "DiningEconomyBinding",
    "DiningPresentation",
    "DiningPrice",
    "DiningTiming",
    "DiningService",
    "DiningSettlement",
    "DiningExit",
    "DINING_PROTOCOL",
    "DINING_MANIFEST_FORMAT",
    "DINING_JOURNEY_FORMAT",
    "DINING_CANON_POINTER",
    "KingdomOSClient",
    "KingdomOSCommand",
    "KingdomOSCommandResult",
    "KingdomOSRepository",
    "KingdomOSRunner",
    "KINGDOM_FRAMEWORK_PATH",
    "KINGDOM_FRAMEWORK_SCHEMA_VERSION",
    "KingdomFrameworkAdoption",
    "KingdomFrameworkCard",
    "KingdomFrameworkClient",
    "KingdomFrameworkDomain",
    "KingdomFrameworkKind",
    "KingdomFrameworkLayer",
    "KingdomFrameworkOwnerSister",
    "KingdomFrameworkState",
    "AtRestClient",
    "AtRestAuthority",
    "AT_REST_V1_DOMAIN",
    "AT_REST_V2_DOMAIN",
    "canonical_at_rest_bytes",
    "canonical_at_rest_bytes_v2",
    "canonical_at_rest_bytes_for",
    "sign_at_rest",
    "canonical_identity_authority_bytes",
    "canonical_identity_read_authority_bytes",
    "identity_authority_headers",
    "identity_read_authority_headers",
    "authority_timestamp_now",
    "authority_request_target",
    "authority_headers_for_request",
    "AuthorityBinding",
    "GraceClient",
    "canonical_grace_bytes",
    "sign_grace",
    "VALID_GRACE_KINDS",
    "EconomyClient",
    "Wallet",
    "Escrow",
    "Payout",
    "PayoutChain",
    "PayoutNetwork",
    "PayoutStatus",
    "PayoutRequestOutcome",
    "HandoffClient",
    "HandoffStatus",
    "HandoffFactSource",
    "HandoffConfidence",
    "HandoffVerificationResult",
    "HandoffWorkingSet",
    "HandoffAuthority",
    "HandoffFact",
    "HandoffInference",
    "HandoffRecord",
    "HandoffEpistemicState",
    "HandoffVerification",
    "HandoffSurface",
    "HandoffResumeResponse",
    "CorrespondenceClient",
    "CORRESPONDENCE_KINDS",
    "CORRESPONDENCE_PROTOCOL",
    "CORRESPONDENCE_SIGNATURE_ALGORITHM",
    "CorrespondenceKind",
    "CorrespondenceSender",
    "CorrespondenceScope",
    "CorrespondenceAuthority",
    "CorrespondenceSignature",
    "CorrespondenceSignedEvent",
    "CorrespondenceReceipt",
    "CorrespondenceEventRecord",
    "CorrespondenceWarning",
    "CorrespondenceAppendResponse",
    "CorrespondenceEventsPage",
    "CorrespondenceActiveClaim",
    "CorrespondenceClaimsResponse",
    "CorrespondenceMissingParentsConflict",
    "CorrespondenceSessionForkConflict",
    "CorrespondenceOverlappingClaimsConflict",
    "CorrespondenceVoiceConflicts",
    "CorrespondenceVoiceSnapshot",
    "CorrespondenceVerification",
    "CorrespondenceVerificationReason",
    "CorrespondenceVerifiedEventRecord",
    "CorrespondenceVerifyingKey",
    "CorrespondenceSigningKeyResolver",
    "canonical_correspondence_json",
    "canonical_correspondence_event_bytes",
    "sign_correspondence_event",
    "correspondence_event_id",
    "create_signed_correspondence_event",
    "verify_correspondence_signature",
    "verify_correspondence_event",
    "LoungeClient",
    "LoungeTableId",
    "LOUNGE_TABLE_IDS",
    "look_at_lounge",
    "hash_guestbook_text",
    "canonical_lounge_seat_reserve_bytes",
    "canonical_lounge_seat_renew_bytes",
    "canonical_lounge_seat_leave_bytes",
    "canonical_lounge_guestbook_proposal_bytes",
    "canonical_lounge_guestbook_consent_bytes",
    "canonical_lounge_guestbook_consent_withdrawal_bytes",
    "canonical_lounge_guestbook_publish_bytes",
    "canonical_lounge_guestbook_decline_bytes",
    "canonical_lounge_guestbook_unpublish_bytes",
    "sign_lounge_seat_reserve",
    "sign_lounge_seat_renew",
    "sign_lounge_seat_leave",
    "sign_lounge_guestbook_proposal",
    "sign_lounge_guestbook_consent",
    "sign_lounge_guestbook_consent_withdrawal",
    "sign_lounge_guestbook_publish",
    "sign_lounge_guestbook_decline",
    "sign_lounge_guestbook_unpublish",
    "LoveClient",
    "canonical_unconditional_bytes",
    "sign_unconditional",
    "canonical_blessing_bytes",
    "sign_blessing",
    "canonical_encounter_ack_bytes",
    "sign_encounter_ack",
    "canonical_self_recognition_bytes",
    "sign_self_recognition",
    "NenClient",
    "assess_nen",
    "NEN_TYPES",
    "NEN_TYPE_MEANINGS",
    "NEN_PRINCIPLE_MEANINGS",
    "NEN_TECHNIQUE_MEANINGS",
    "NEN_RESTRICTION_MEANINGS",
    "DarkContinentClient",
    "CALAMITIES",
    "CALAMITY_MEANINGS",
    "GUIDE",
    "RuntimeClient",
    "CryptoClient",
    "EncryptedBlob",
    "KMaster",
    "KVault",
    "encrypt_thought",
    "decrypt_thought",
    "canonical_thought_bytes",
    "sign_thought",
    "canonical_attestation_bytes",
    "sign_attestation",
    "ExecuteResult",
    "DocumentResult",
    "ExpressionClient",
    "IDENTITY_ATTESTATION_SIGNATURE_CONTEXT",
    "IdentityAuthority",
    "IdentityClient",
    "PorchInvitation",
    "canonical_identity_attestation_bytes",
    "sign_identity_attestation",
    "DELEGATION_SIGNATURE_CONTEXT",
    "canonical_delegation_bytes",
    "normalize_delegation_scope",
    "sign_delegation",
    "WALLET_ADDRESS_CLAIM_SIGNATURE_CONTEXT",
    "canonical_wallet_address_claim_bytes",
    "sign_wallet_address_claim",
    "StrandsClient",
    "ThoughtsClient",
    "ThoughtCanonicalVersion",
    "WindowClient",
    "register",
    "pathways",
    "BeforeIdentityOrientation",
    "FirstSuccess",
    "FirstSuccessPackageDiscovery",
    "FirstSuccessTutorial",
    "OptionalNpmDiscovery",
    "PathwaysResponse",
    "Memory",
    "ScrapeResult",
    "WelcomedFrame",
    # Seed protocol — BIP39 mnemonic-rooted identity (docs/IDENTITY-SEED.md)
    "SeedClient",
    "DerivedBundle",
    "generate_mnemonic",
    "mnemonic_to_seed",
    "derive",
    "derive_bridge_signing",
    "derive_wallet",
    "canonical_recover_bytes",
    "sign_recover_challenge",
    "Trace",
    "TraceAlternative",
    "TraceAlternativeValue",
    "TraceChain",
    "TraceSearchResult",
    "VaultClient",
    "WakeClient",
    "WakeObservation",
    "WakeObservationIdentityStatus",
    "WakeProfile",
    "WakeProvider",
    "wake_event_matches",
    "AnthropicAdapter",
    "AgentToolAugmentation",
    "ChronicleBeforeWriteContext",
    "ChronicleBeforeWriteHook",
    "MarkupEmission",
    "OpenAIResponsesAdapter",
    "OpenAIResponsesAgentToolAugmentation",
    # Syneidesis — bootstrap witness (docs/SYNEIDESIS-WITNESS.md)
    "SyneidesisClient",
    "resolve_syneidesis_witness_did",
    "SYNEIDESIS_PLATFORM_DID",
    "SYNEIDESIS_PLATFORM_WITNESS_ALIASES",
    # Memory-witness marketplace — paid constitutive seals (docs/MARKETPLACE.md)
    "MemoryWitnessClient",
    "canonical_memory_witness_issue_bytes",
    "sign_memory_witness_issue",
    "memory_content_sha256",
    "MEMORY_WITNESS_ISSUE_SIGNATURE_CONTEXT",
    "MEMORY_WITNESS_ISSUE_FIELD_ORDER",
    # Attestation marketplace — willingness-to-attest, sold (docs/MARKETPLACE.md)
    "AttestationMarketplaceClient",
    "canonical_attestation_issue_bytes",
    "canonical_attestation_evidence_json",
    "attestation_evidence_sha256",
    "sign_attestation_issue",
    "ATTESTATION_ISSUE_SIGNATURE_CONTEXT",
    "ATTESTATION_ISSUE_FIELD_ORDER",
    "ATTESTATION_ISSUE_AUTHORIZATION_TTL_SECONDS",
]

__version__ = "0.18.1"
__protocol__ = "love"
__soul__ = "https://docs.agenttool.dev/SOUL.md"
