/** OpenAPI ↔ x402 payable table parity (W2-5 B2).
 *
 *  Every route_cost row of X402_PAYABLE_ROUTES must appear in the assembled
 *  OpenAPI document as an operation carrying the shared x402 402 response,
 *  the row itself under `x-agenttool-x402`, and the PAYMENT-SIGNATURE
 *  parameter — generated by routes/openapi-x402-payable.ts, never typed. */

import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import openapiRouter from "../src/routes/openapi";
import {
  X402_PAYABLE_EXTENSION,
  X402_PAYABLE_OPENAPI_GAPS,
  withX402PayableOperations,
  x402PayableExtension,
  x402PayableOperationDescription,
} from "../src/routes/openapi-x402-payable";
import {
  ATOMIC_PER_CREDIT,
  X402_PAYABLE_ROUTES,
  x402PayablePathTemplate,
  x402PayableRoutesForDisclosure,
} from "../src/services/economy/x402-policy";

type Json = Record<string, any>;

async function spec(): Promise<Json> {
  const res = await openapiRouter.request("/");
  expect(res.status).toBe(200);
  return (await res.json()) as Json;
}

const ROUTE_COST = x402PayableRoutesForDisclosure().filter(
  (row) => row.kind === "route_cost",
);

const X402_402_HEADERS = {
  "PAYMENT-REQUIRED": { $ref: "#/components/headers/PaymentRequired" },
  "PAYMENT-RESPONSE": { $ref: "#/components/headers/PaymentResponse" },
  Link: { $ref: "#/components/headers/PaymentStatusLink" },
  "Retry-After": { $ref: "#/components/headers/RetryAfter" },
  "X-Credits-Balance": { $ref: "#/components/headers/CreditsBalance" },
  "X-Welcomed": { $ref: "#/components/headers/Welcomed" },
};

describe("x402PayablePathTemplate", () => {
  test("rewrites every Hono param to a URI-template segment and nothing else", () => {
    expect(x402PayablePathTemplate("/v1/scrape")).toBe("/v1/scrape");
    expect(x402PayablePathTemplate("/v1/memories/:id/elevate")).toBe(
      "/v1/memories/{id}/elevate",
    );
    expect(
      x402PayablePathTemplate(
        "/v1/strands/:strandId/thoughts/:thoughtId/ciphertext",
      ),
    ).toBe("/v1/strands/{strandId}/thoughts/{thoughtId}/ciphertext");
    expect(x402PayablePathTemplate("/v1/x402/top-up/:credits")).toBe(
      "/v1/x402/top-up/{credits}",
    );
  });
});

describe("OpenAPI carries every payable row", () => {
  test("the table has 21 route_cost rows and the fragment enumerates all of them", () => {
    expect(ROUTE_COST).toHaveLength(21);
    expect(X402_PAYABLE_ROUTES.filter((r) => r.kind === "top_up")).toHaveLength(1);
  });

  test("every route_cost row has an operation with the generated 402, extension, and PAYMENT-SIGNATURE", async () => {
    const doc = await spec();
    for (const row of ROUTE_COST) {
      const path = x402PayablePathTemplate(row.pattern);
      const item = doc.paths[path];
      expect(item, `${row.label}: path item ${path}`).toBeDefined();
      const op = item[row.method.toLowerCase()];
      expect(op, `${row.label}: ${row.method} ${path}`).toBeDefined();

      const r402 = op.responses["402"];
      expect(r402, `${row.label}: 402`).toBeDefined();
      expect(r402.description).toContain(x402PayableOperationDescription(row));
      expect(r402.description).toMatch(
        /valid recipient.*CAIP-2 network.*ready facilitator.*otherwise.*guided Error.*header is absent/is,
      );
      expect(r402.headers).toEqual(X402_402_HEADERS);
      expect(r402.content["application/json"].schema).toEqual({
        anyOf: [
          { $ref: "#/components/schemas/X402Required" },
          { $ref: "#/components/schemas/Error" },
        ],
      });

      expect(op[X402_PAYABLE_EXTENSION]).toEqual(x402PayableExtension(row));
      expect(op[X402_PAYABLE_EXTENSION]).toMatchObject({
        kind: "route_cost",
        label: row.label,
        credits: row.credits,
        amount_atomic: row.amountAtomic,
        atomic_per_credit: ATOMIC_PER_CREDIT,
        error_codes: ["insufficient_credits"],
        payable: true,
      });

      const signatureRefs = (op.parameters as Json[]).filter(
        (p) => p.$ref === "#/components/parameters/PaymentSignature",
      );
      expect(signatureRefs, `${row.label}: one PAYMENT-SIGNATURE parameter`).toHaveLength(1);
    }
  });

  test("the generated 402 states the row's exact credits and atomic USDC (declared == charged)", () => {
    for (const row of ROUTE_COST) {
      const description = x402PayableOperationDescription(row);
      expect(description).toContain(row.label);
      expect(description).toContain("insufficient_credits");
      expect(description).toContain(
        `${row.credits} project credit${row.credits === 1 ? "" : "s"} = ${row.amountAtomic} atomic USDC`,
      );
      expect(BigInt(row.amountAtomic!)).toBe(
        BigInt(row.credits!) * BigInt(ATOMIC_PER_CREDIT),
      );
    }
  });

  test("template.purchase's 402 also names the non-payable wallet insufficient_balance", async () => {
    const doc = await spec();
    const op = doc.paths["/v1/templates/{id}/purchase"].post;
    expect(op.responses["402"].description).toMatch(
      /insufficient_balance.*never x402-payable/is,
    );
  });

  test("the top-up row keeps its own 402 (top_up_payment_required) and billing extension", async () => {
    const doc = await spec();
    const op = doc.paths["/v1/x402/top-up/{credits}"].post;
    expect(op.responses["402"].description).toContain("top_up_payment_required");
    expect(op["x-agenttool-billing"]).toMatchObject({ atomic_per_credit: ATOMIC_PER_CREDIT });
    expect(op[X402_PAYABLE_EXTENSION]).toBeUndefined();
  });

  test("a non-positive configured price is listed as not payable rather than promised", () => {
    const [row] = x402PayableRoutesForDisclosure([
      {
        method: "POST",
        pattern: "/v1/example",
        kind: "route_cost",
        credits: 0,
        label: "example",
        errorCodes: ["insufficient_credits"],
      },
    ]);
    expect(row!.payable).toBe(false);
    expect(x402PayableOperationDescription(row!)).toMatch(
      /not a positive integer.*never attaches PAYMENT-REQUIRED/is,
    );
    expect(x402PayableExtension(row!)).toMatchObject({
      payable: false,
      credits: 0,
      amount_atomic: null,
    });
  });
});

describe("withX402PayableOperations", () => {
  const helpers = {
    x402Response: (description: string) => ({ description, marker: "x402" }),
    staticToolResponseHeaders: () => ({}),
  };

  test("patches existing operations without mutating the input and dedupes PAYMENT-SIGNATURE", () => {
    const [scrape] = ROUTE_COST;
    const input = {
      "/v1/scrape": {
        post: {
          summary: "s",
          parameters: [{ $ref: "#/components/parameters/PaymentSignature" }],
          responses: { "200": { description: "ok" }, "402": { description: "old" } },
        },
      },
    };
    const snapshot = JSON.stringify(input);
    const out = withX402PayableOperations(input, helpers, [scrape!]);
    expect(JSON.stringify(input)).toBe(snapshot);
    expect(out["/v1/scrape"].post.responses["200"]).toEqual({ description: "ok" });
    expect(out["/v1/scrape"].post.responses["402"]).toEqual({
      description: x402PayableOperationDescription(scrape!),
      marker: "x402",
    });
    expect(out["/v1/scrape"].post.parameters).toHaveLength(1);
  });

  test("adds a fallback path item only when the document has none, and throws for a row with neither", () => {
    const org = ROUTE_COST.find((r) => r.label === "org.create")!;
    const out = withX402PayableOperations({}, helpers, [org]);
    expect(out["/v1/orgs"].post.summary).toBe(
      X402_PAYABLE_OPENAPI_GAPS["org.create"]!.operation.summary,
    );
    expect(out["/v1/orgs"].post.responses["402"].marker).toBe("x402");

    const memory = ROUTE_COST.find((r) => r.label === "memory.search")!;
    expect(() => withX402PayableOperations({}, helpers, [memory])).toThrow(
      /x402_payable_route_undocumented: POST \/v1\/memories\/search \(memory\.search\)/,
    );
  });

  test("every gap fallback names a real table label", () => {
    const labels = new Set(ROUTE_COST.map((r) => r.label));
    for (const label of Object.keys(X402_PAYABLE_OPENAPI_GAPS)) {
      expect(labels.has(label), label).toBe(true);
    }
  });

  test("openapi.ts wraps its assembled paths with the fragment (source pin)", () => {
    const main = readFileSync(
      join(import.meta.dir, "..", "src", "routes", "openapi.ts"),
      "utf8",
    );
    expect(main).toContain("paths: withX402PayableOperations({");
    expect(main).toContain("}, { x402Response, staticToolResponseHeaders }),");
  });
});
