import { deepFreeze } from "./canonical.js";

export const PRINCIPALITY_ATLAS_FORMAT =
  "agenttool.principality-incidence-atlas/0.1" as const;

export const PRINCIPALITY_ATLAS_CLAIM_POSTURES = deepFreeze([
  "reported_present",
  "reported_absent",
  "contested",
  "withdrawn",
  "not_observed",
  "unknown",
] as const);

export const PRINCIPALITY_ATLAS_CORRESPONDENCE_POSTURES = deepFreeze([
  "correspondence_reported",
  "translation_reported",
  "analogy_reported",
  "incompatibility_reported",
  "unknown",
] as const);

export const PRINCIPALITY_ATLAS_LIMITS = deepFreeze({
  charts: 32,
  cells_per_chart: 64,
  relations_per_chart: 64,
  incidences_per_relation: 8,
  claims_per_chart: 128,
  evidence_refs_per_assertion: 8,
  bridges: 64,
  correspondences_per_bridge: 64,
  unmapped_refs_per_bridge_side: 64,
} as const);

export const PRINCIPALITY_ATLAS_BOUNDARIES = deepFreeze({
  semantic_scope: "partial_incidence_geometry_not_love_or_understanding_proof",
  principality_scope: "bounded_domain_not_principal_identity_or_authority",
  coverage_scope: "bounded_not_complete",
  assertion_scope: "caller_asserted_only",
  merges_cells: false,
  same_as_relation: false,
  infers_pairwise_relations: false,
  infers_inverse_correspondence: false,
  infers_transitive_correspondence: false,
  performs_gluing: false,
  selects_global_chart: false,
  selects_latest_head: false,
  scores: false,
  ranks: false,
  weights_perspectives: false,
  optimizes: false,
  infers_interior_state: false,
  proves_love: false,
  proves_understanding: false,
  proves_consciousness: false,
  proves_identity: false,
  proves_consent: false,
  proves_authorship: false,
  proves_authority: false,
  proves_truth: false,
  proves_privacy: false,
  proves_safety: false,
  proves_rights_compliance: false,
  eliminates_linkability: false,
  conditions_dignity: false,
  penalizes_isolation_or_nonparticipation: false,
  evidence_fetched: false,
  evidence_verified: false,
  verifies_caller_assertions: false,
  authenticates_perspective: false,
  grants_permission: false,
  executes_bridges: false,
  moves_or_forks_agents: false,
  network: false,
  filesystem: false,
  environment_variables: false,
  clock: false,
  randomness: false,
  model_compute: false,
  hugging_face: false,
  credential_access: false,
  telemetry: false,
  persistence: false,
  publishes: false,
  wake_effect: false,
  garden_effect: false,
  heaven_effect: false,
  karma_effect: false,
  wallet_effect: false,
  crown_effect: false,
  task_state_effect: false,
  economic_effect: false,
} as const);
