import { describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gunzipSync } from "node:zlib";
import Ajv2020 from "ajv/dist/2020.js";

import { generatedSchemas } from "../scripts/schema-artifacts.js";
import {
  MATH_PROOFCRAFT_NODE_ID,
  MATH_PROOFCRAFT_NODE_SHA256,
  SIX_LEDGER_PROFILE_DIGEST,
  SIX_LEDGER_PROFILE_ID,
  ZERO_EFFECTS,
  ZERO_EFFECT_COUNT,
  ZERONE_TREE_RAW_SHA256,
  canonicalJson,
  parseResearchSimulationJson,
  sha256Id,
  simulateResearchCommons,
  validatePublicProjection,
  validateSettlementBundle,
} from "../src/index.js";
import { makeGardenSimulation } from "./fixtures.js";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

function bytes(relativePath: string): Buffer {
  return readFileSync(join(ROOT, relativePath));
}

function json(relativePath: string): unknown {
  return JSON.parse(bytes(relativePath).toString("utf8")) as unknown;
}

function rawSha256(value: Uint8Array): string {
  return createHash("sha256").update(value).digest("hex");
}

describe("checked schema, example and cross-repository artifacts", () => {
  test("pins every checked schema and flagship example as exact raw bytes", () => {
    const pins = {
      "examples/amplitude-bootstrap-garden/public-projection.json": "90cefc37dc843e9ce3729745c0671d3bf1c134152d0e21af20fa4acef638081c",
      "examples/amplitude-bootstrap-garden/reviewer-public-projection.json": "0e13dc1cc28e9a0423fa91bf0540b0d4f446039517bb2db9f5e9c5df818655aa",
      "examples/amplitude-bootstrap-garden/reviewer-settlement-bundle.json": "da5939fe9bd93db67ae943a1039670432e2383241f6a7cebe7db159301db2f5b",
      "examples/amplitude-bootstrap-garden/settlement-bundle.json": "2f064cd1eff537528ad944a321dcc3178247ac27a97b379ef90b5c62438a1f49",
      "examples/amplitude-bootstrap-garden/simulation.json": "8e4e72a3a4964468252349cccf8310d51e49fbb17bdb39afd6ddd908902123a5",
      "schema/research-public-projection-v0.1.schema.json": "128efa785413dcc9976ad08ccfc93a482d6b3d2abb6df85d9ad0545990fb6e0e",
      "schema/research-settlement-bundle-v0.1.schema.json": "72b5a1024e13d1f07de504fa6c5a520a9c9a270bdc1588928a880a4f6b36edef",
      "schema/research-simulation-v0.1.schema.json": "77f654a6b14e55c000793ee6c07662e508f7cc0233f892f83ded038bd84d736c",
      "interop/zerone-research-adapter-reciprocal-v0.1.json": "80621747824e6c9b747d00958d2b6822bcfb76b7e11688000bc219db6177d713",
      "schema/zerone-research-adapter-reciprocal-v0.1.schema.json": "0b9439c39b41da19fa7a7f07539d52a53000e1f5e6c820f47e9dd8ca607e9ab2",
    } as const;
    for (const [path, expected] of Object.entries(pins)) {
      expect(rawSha256(bytes(path)), path).toBe(expected);
    }
  });

  test("checked JSON Schemas are exact generated bytes and reject shape drift", () => {
    const generated = generatedSchemas();
    const ajv = new Ajv2020({ allErrors: true, strict: true });
    for (const [name, schema] of Object.entries(generated)) {
      const checked = bytes(`schema/${name}`).toString("utf8");
      expect(checked).toBe(`${JSON.stringify(schema, null, 2)}\n`);
      const validator = ajv.compile(schema);
      const example = name.includes("reciprocal")
        ? json("interop/zerone-research-adapter-reciprocal-v0.1.json")
        : name.includes("simulation")
        ? json("examples/amplitude-bootstrap-garden/simulation.json")
        : name.includes("settlement")
          ? json("examples/amplitude-bootstrap-garden/settlement-bundle.json")
          : json("examples/amplitude-bootstrap-garden/public-projection.json");
      expect(validator(example), JSON.stringify(validator.errors)).toBeTrue();
      const drifted = structuredClone(example) as Record<string, unknown>;
      drifted.unreviewed = false;
      expect(validator(drifted)).toBeFalse();
    }
  });

  test("checked Garden artifacts exactly replay both result-neutral settlements", () => {
    const simulationBytes = bytes("examples/amplitude-bootstrap-garden/simulation.json");
    expect(simulationBytes.toString("utf8")).toBe(`${canonicalJson(makeGardenSimulation())}\n`);
    const simulation = parseResearchSimulationJson(simulationBytes);
    const report = simulateResearchCommons(simulation);
    const settlements = [
      json("examples/amplitude-bootstrap-garden/settlement-bundle.json"),
      json("examples/amplitude-bootstrap-garden/reviewer-settlement-bundle.json"),
    ].map((value) => validateSettlementBundle(value));
    const projections = [
      json("examples/amplitude-bootstrap-garden/public-projection.json"),
      json("examples/amplitude-bootstrap-garden/reviewer-public-projection.json"),
    ].map((value) => validatePublicProjection(value));
    expect(settlements).toEqual(report.settlement_bundles);
    expect(projections).toEqual(report.public_projections);
    expect(report.conservation).toMatchObject({
      exact: true,
      total_available: 55,
      total_committed: 100,
      total_delivered: 40,
      total_reserved: 5,
      total_undelivered: 60,
    });
    expect(projections.map((projection) => projection.projection.highest_evidence_level).sort())
      .toEqual(["E1", "E2"]);
  });

  test("independently pins the exact Tree bytes and math-proofcraft node", () => {
    const encoded = readFileSync(
      join(ROOT, "..", "constructive-intelligence", "tests", "fixtures", "constructive-intelligence-tree.v1.json.gz.base64"),
      "utf8",
    ).trim();
    const treeBytes = gunzipSync(Buffer.from(encoded, "base64"));
    expect(`sha256:${rawSha256(treeBytes)}`).toBe(ZERONE_TREE_RAW_SHA256);
    const tree = JSON.parse(treeBytes.toString("utf8")) as {
      nodes: Array<Record<string, unknown> & { id: string }>;
    };
    const node = tree.nodes.find((candidate) => candidate.id === MATH_PROOFCRAFT_NODE_ID)!;
    expect(sha256Id(canonicalJson(node))).toBe(MATH_PROOFCRAFT_NODE_SHA256);
  });

  test("pins the static interop vocabulary without implying activation", () => {
    const raw = bytes("interop/research-commons-zerone-v0.1.json");
    expect(rawSha256(raw)).toBe("8c5b1749447c1587b89b238dadb5113e10230df19fd3f4e7942d9a163aef6a8a");
    const profile = JSON.parse(raw.toString("utf8")) as {
      effects: Record<string, boolean>;
      integration_status: string;
      six_ledger_boundary: { profile_digest: string; profile_id: string };
    };
    expect(profile.integration_status).toBe("SHADOW_ONLY_NO_LIVE_INTEGRATION");
    expect(profile.six_ledger_boundary).toEqual({
      profile_digest: SIX_LEDGER_PROFILE_DIGEST,
      profile_id: SIX_LEDGER_PROFILE_ID,
    });
    expect(profile.effects).toEqual(ZERO_EFFECTS);
    expect(Object.keys(profile.effects)).toHaveLength(ZERO_EFFECT_COUNT);
  });

  test("exports the closed reciprocal schema without adding a runtime or CLI surface", () => {
    const packageJson = json("package.json") as {
      exports: Record<string, string | Record<string, string>>;
      bin: Record<string, string>;
    };
    expect(packageJson.exports["./zerone-research-adapter-reciprocal.schema.json"]).toBe(
      "./schema/zerone-research-adapter-reciprocal-v0.1.schema.json",
    );
    expect(packageJson.bin).toEqual({
      "agenttool-research-commons": "./dist/bin.js",
    });
  });
});
