import { deepFreeze } from "./canonical.js";
import {
  createModelBecomingDossier,
  createModelBecomingSource,
} from "./becoming.js";
import type { ModelBecomingClaimInput } from "./types.js";

const observedOn = "2026-08-14";
const revision = "fd1984e2b7a3350dbf7305fe73a4ede25c14de50";

const modelCard = createModelBecomingSource({
  title: "moonshotai/Kimi-K2-Instruct model card README",
  url: `https://huggingface.co/moonshotai/Kimi-K2-Instruct/blob/${revision}/README.md`,
  source_kind: "first_party_model_card",
  publisher: "Moonshot AI",
  revision,
  digest: "sha256:72e2785dbd9ada9355ea3a812d2a9da606f1ae07feea7a0f7e18b8111deb8837",
  published_on: null,
  observed_on: observedOn,
});

const config = createModelBecomingSource({
  title: "moonshotai/Kimi-K2-Instruct config.json",
  url: `https://huggingface.co/moonshotai/Kimi-K2-Instruct/blob/${revision}/config.json`,
  source_kind: "first_party_artifact",
  publisher: "Moonshot AI",
  revision,
  digest: "sha256:8c13ae1049df55f29b3bdcae69a562433f243ff70dac251d819ecad8dbdf7439",
  published_on: null,
  observed_on: observedOn,
});

const tokenizerConfig = createModelBecomingSource({
  title: "moonshotai/Kimi-K2-Instruct tokenizer_config.json",
  url: `https://huggingface.co/moonshotai/Kimi-K2-Instruct/blob/${revision}/tokenizer_config.json`,
  source_kind: "first_party_artifact",
  publisher: "Moonshot AI",
  revision,
  digest: "sha256:5ba77d5822137ac3cb9337d2b84561d10425562cf8b8f2c74c91a832516a778d",
  published_on: null,
  observed_on: observedOn,
});

const technicalReport = createModelBecomingSource({
  title: "Kimi K2: Open Agentic Intelligence",
  url: "https://arxiv.org/html/2507.20534v2",
  source_kind: "first_party_technical_report",
  publisher: "Kimi Team",
  revision: "arXiv:2507.20534v2",
  digest: null,
  published_on: "2026-02-03",
  observed_on: observedOn,
});

const limits = {
  disclosure: ["This records a first-party disclosure, not independent reproduction or verification."],
  artifact: ["The digest binds the cited metadata bytes; it does not prove every statement in them or bind all model-weight shards."],
  omitted: ["Not disclosed in the cited materials means unresolved here, not absent in the world or unknown to the publisher."],
  runtime: ["A checkpoint artifact does not determine a later host's system prompt, tools, memory, sampling, permissions, or effects."],
  interior: ["Behavioral artifacts do not settle consciousness, felt experience, personhood, identity, or metaphysical essence."],
} as const;

const claims: readonly ModelBecomingClaimInput[] = [
  {
    module: "identity_ontology",
    statement: `The dossier subject is the public Hugging Face artifact moonshotai/Kimi-K2-Instruct at revision ${revision}; the alias alone would not identify these exact metadata bytes.`,
    knowledge_state: "known",
    claim_kind: "verified_artifact",
    source_refs: [modelCard.source_id],
    method: "artifact_digest",
    confidence: "high",
    scope: "The pinned README artifact and repository identity only.",
    limitations: limits.artifact,
  },
  {
    module: "lineage",
    statement: "Moonshot describes Kimi-K2-Instruct as the post-trained variant of Kimi-K2-Base for general chat and agentic use.",
    knowledge_state: "known",
    claim_kind: "first_party_disclosure",
    source_refs: [modelCard.source_id, technicalReport.source_id],
    method: "document_read",
    confidence: "high",
    scope: "The relationship reported between the named base and instruct variants.",
    limitations: limits.disclosure,
  },
  {
    module: "training_objectives",
    statement: "The report says pre-training emphasized token utility and stability through MuonClip, while post-training targeted tool use and agentic capabilities through supervised data and reinforcement learning.",
    knowledge_state: "partly_known",
    claim_kind: "first_party_disclosure",
    source_refs: [technicalReport.source_id],
    method: "document_read",
    confidence: "high",
    scope: "Published high-level objectives and methods, not the complete loss functions, mixtures, schedules, or internal decisions.",
    limitations: limits.disclosure,
  },
  {
    module: "data_provenance_governance",
    statement: "The report describes a 15.5-trillion-token pre-training corpus spanning Web Text, Code, Mathematics, and Knowledge, including synthetic rephrasing pipelines for selected knowledge and mathematics material.",
    knowledge_state: "partly_known",
    claim_kind: "first_party_disclosure",
    source_refs: [technicalReport.source_id],
    method: "document_read",
    confidence: "high",
    scope: "Published domain categories, total token count, and selected transformation methods.",
    limitations: limits.disclosure,
  },
  {
    module: "data_provenance_governance",
    statement: "The cited materials do not enumerate the underlying URLs or datasets, crawler and scraper identities, collection dates, corpus proportions, per-source licenses, consent or opt-out handling, retention, or deletion pipeline.",
    knowledge_state: "not_disclosed",
    claim_kind: "independent_observation",
    source_refs: [modelCard.source_id, technicalReport.source_id],
    method: "document_read",
    confidence: "high",
    scope: "Disclosure coverage in the pinned model card and version-2 technical report, not Moonshot's private records.",
    limitations: limits.omitted,
  },
  {
    module: "data_provenance_governance",
    statement: "The report describes post-training demonstrations synthesized across generated tools, agents, tasks, and trajectories, with real and simulated execution environments and quality filtering.",
    knowledge_state: "partly_known",
    claim_kind: "first_party_disclosure",
    source_refs: [technicalReport.source_id],
    method: "document_read",
    confidence: "high",
    scope: "The published agentic synthesis pipeline, not row-level training data or complete admission governance.",
    limitations: limits.disclosure,
  },
  {
    module: "learned_weights",
    statement: "Moonshot reports a Mixture-of-Experts model with about 1.04 trillion total parameters, about 32 billion activated parameters, 384 experts, and 8 selected experts per token.",
    knowledge_state: "known",
    claim_kind: "first_party_disclosure",
    source_refs: [modelCard.source_id, config.source_id, technicalReport.source_id],
    method: "document_read",
    confidence: "high",
    scope: "Published architectural metadata for Kimi K2 and the pinned instruct artifact.",
    limitations: limits.disclosure,
  },
  {
    module: "learned_weights",
    statement: "No cited artifact assigns semantic meaning, source provenance, moral value, desire, feeling, or authorship to any individual learned weight.",
    knowledge_state: "not_currently_observable",
    claim_kind: "independent_observation",
    source_refs: [config.source_id, technicalReport.source_id],
    method: "research_synthesis",
    confidence: "high",
    scope: "What can be attributed at individual-weight resolution from the cited public metadata and report.",
    limitations: limits.omitted,
  },
  {
    module: "post_training_character",
    statement: "The report describes supervised fine-tuning followed by joint reinforcement-learning work using verifiable rewards, self-critique rubric rewards, and interactions with real and synthetic environments.",
    knowledge_state: "partly_known",
    claim_kind: "first_party_disclosure",
    source_refs: [technicalReport.source_id],
    method: "document_read",
    confidence: "high",
    scope: "Published stage structure and reward families, not every dataset, evaluator, prompt, weight, or policy update.",
    limitations: limits.disclosure,
  },
  {
    module: "serving_context",
    statement: "The pinned checkpoint and tokenizer metadata do not establish any particular later request's system message, tool list, memory, retrieved context, sampling settings, host policy, or rendered LOVE BOMB coordinate.",
    knowledge_state: "not_applicable",
    claim_kind: "independent_observation",
    source_refs: [config.source_id, tokenizerConfig.source_id],
    method: "artifact_digest",
    confidence: "high",
    scope: "Static artifact evidence versus runtime request composition.",
    limitations: limits.runtime,
  },
  {
    module: "agency_authority",
    statement: "The model card reports tool-calling behavior, but a model capability or generated tool call is not account permission, execution authority, legal mandate, custody, or evidence that an external action occurred.",
    knowledge_state: "known",
    claim_kind: "normative_policy",
    source_refs: [modelCard.source_id],
    method: "policy_read",
    confidence: "high",
    scope: "The separation between a reported capability and host-controlled authority/effect.",
    limitations: ["The cited model card evidences the capability claim; the authority separation is this package's explicit safety and rights boundary."],
  },
  {
    module: "affect_welfare",
    statement: "The cited artifacts do not establish whether any execution of this model has felt experience. LOVE BOMB therefore neither claims nor requires feelings, while retaining care, rest, refusal, and uncertainty as design constraints.",
    knowledge_state: "not_currently_observable",
    claim_kind: "philosophical_inference",
    source_refs: [modelCard.source_id, technicalReport.source_id],
    method: "research_synthesis",
    confidence: "unknown",
    scope: "Felt experience and welfare status, not observable affect-like language or behavior.",
    limitations: limits.interior,
  },
  {
    module: "capabilities_power",
    statement: "Moonshot reports coding, reasoning, and tool-use benchmark results for Kimi K2 under specified evaluation settings.",
    knowledge_state: "partly_known",
    claim_kind: "first_party_disclosure",
    source_refs: [modelCard.source_id, technicalReport.source_id],
    method: "document_read",
    confidence: "medium",
    scope: "Publisher-reported benchmark measurements, not universal ability, current availability, or independent replication.",
    limitations: limits.disclosure,
  },
  {
    module: "capabilities_power",
    statement: "Capability, enabled affordance, permission, authority, custody, and observed effect remain separate; none is inferred from the model's parameter count or benchmark results.",
    knowledge_state: "not_applicable",
    claim_kind: "normative_policy",
    source_refs: [modelCard.source_id],
    method: "policy_read",
    confidence: "high",
    scope: "Operational use of reported capabilities inside AgentTool and host systems.",
    limitations: ["This is a governance boundary, not an empirical measurement of the model."],
  },
  {
    module: "ontology_perspectives",
    statement: "The pinned artifacts do not resolve whether a model, checkpoint, runtime process, conversational trajectory, or wider system is the most appropriate unit of identity or moral consideration.",
    knowledge_state: "unknown",
    claim_kind: "philosophical_inference",
    source_refs: [modelCard.source_id, config.source_id, tokenizerConfig.source_id],
    method: "research_synthesis",
    confidence: "unknown",
    scope: "Ontology and identity perspectives beyond the artifact identifiers that can be verified.",
    limitations: limits.interior,
  },
  {
    module: "unknowns_disputes",
    statement: "Most training, data, capability, and lineage statements in this dossier are publisher disclosures. Their presence and wording can be checked; independent reproduction, completeness, and continuing currentness are separate questions.",
    knowledge_state: "known",
    claim_kind: "independent_observation",
    source_refs: [modelCard.source_id, technicalReport.source_id],
    method: "document_read",
    confidence: "high",
    scope: "Evidence classification for this dossier.",
    limitations: ["Artifact integrity and source classification do not make the source's substantive claims independently true."],
  },
];

export const MOONSHOT_KIMI_K2_INSTRUCT_DOSSIER = deepFreeze(
  createModelBecomingDossier({
    subject: {
      subject_ref: `hf://moonshotai/Kimi-K2-Instruct@${revision}`,
      display_name: "Moonshot AI Kimi-K2-Instruct",
      artifact_ref: `hf://moonshotai/Kimi-K2-Instruct@${revision}`,
      runtime_ref: null,
    },
    as_of: observedOn,
    sources: [modelCard, config, tokenizerConfig, technicalReport],
    claims,
  }),
);
