export {
  ASSESSMENT_NON_CLAIMS,
  BINDING_BOUNDARIES,
  BINDING_PURPOSES,
  LIMITS,
  OBSERVATION_BOUNDARIES,
  PACKAGE_NAME,
  PACKAGE_VERSION,
  PUBLICATION_PATH,
  RECORD_SCHEMAS,
  REVOCATION_REASONS,
  SIGNING_DOMAINS,
} from "./constants.js";

export {
  canonicalJson,
  canonicalRecordSha256,
  decodeCanonicalRecord,
  domainSeparatedId,
  encodeCanonicalRecord,
  signingBytes,
  signingDigest,
  snapshotJsonData,
} from "./canonical.js";

export { strictEd25519Verify } from "./crypto.js";

export {
  assessPublicSurfaceBinding,
  assertVerifiedPublicSurfaceBinding,
  assertVerifiedPublicSurfaceRevocation,
  createPublicSurfaceObservation,
  publicSurfaceAssessmentId,
  publicSurfaceBindingDocumentSha256,
  sealPublicSurfaceBinding,
  sealPublicSurfaceRevocation,
  surfaceBindingDigest,
  surfaceBindingId,
  surfaceObservationId,
  surfaceRevocationDigest,
  surfaceRevocationId,
  verifyPublicSurfaceBinding,
  verifyPublicSurfaceBindingSignature,
  verifyPublicSurfaceRevocation,
  verifyPublicSurfaceRevocationSignature,
  type AssessPublicSurfaceBindingInput,
} from "./protocol.js";

export {
  assertCanonicalHttpsOrigin,
  assertCanonicalHttpsUrl,
  assertCanonicalInstant,
  assertCanonicalUuid,
  assertSha256Id,
  publicSurfaceBindingCanonicalBodySha256,
  validateIdentityKeyEvidence,
  validatePublicSurfaceAssessment,
  validatePublicSurfaceAssessmentCore,
  validatePublicSurfaceBinding,
  validatePublicSurfaceBindingCore,
  validatePublicSurfaceObservation,
  validatePublicSurfaceObservationCore,
  validatePublicSurfaceRevocation,
  validatePublicSurfaceRevocationCore,
} from "./validation.js";

export { PublicSurfaceBindingError, type PublicSurfaceBindingErrorCode } from "./errors.js";

export type {
  BindingPurpose,
  BindingSubject,
  CollectorDescriptor,
  Ed25519Authority,
  EvidenceMatchAssessment,
  FreshnessAssessment,
  IdentityKeyEvidence,
  KeyAuthorizationAssessment,
  MathVerifiedBinding,
  MathVerifiedRevocation,
  OriginConfirmationAssessment,
  PublicSurfaceAssessment,
  PublicSurfaceAssessmentCore,
  PublicSurfaceBinding,
  PublicSurfaceBindingCore,
  PublicSurfaceObservation,
  PublicSurfaceObservationCore,
  PublicSurfaceRevocation,
  PublicSurfaceRevocationCore,
  RecordSignature,
  RecordSigner,
  RedirectObservation,
  RequestAuthenticationObservation,
  RevocationAssessment,
  RevocationReason,
  RobotsSnapshot,
  Sha256Id,
  SignatureAssessment,
  UsagePreference,
} from "./types.js";
