export {
  MAX_ALCHEMY_CALL_DURATION_MS,
  MAX_ALCHEMY_CODE_BYTES,
  MAX_ALCHEMY_RESPONSE_BYTES,
  MAX_ALCHEMY_TRANSACTION_INPUT_BYTES,
  MAX_ALCHEMY_TRANSFER_BLOCK_SPAN,
  MAX_ALCHEMY_TRANSFER_CONTRACTS,
  ALCHEMY_TRANSFER_CURSOR_TTL_MS,
  MAX_ALCHEMY_TRANSFER_PAGE_SIZE,
  createAlchemyReadClient,
} from "./client.js";
export {
  AlchemyReadError,
  type AlchemyReadErrorCode,
} from "./errors.js";
export {
  ALCHEMY_NETWORKS,
  getAlchemyNetwork,
} from "./networks.js";
export * from "./evidence.js";
export type {
  AlchemyAssetTransfer,
  AlchemyAssetTransfersRpcParams,
  AlchemyChain,
  AlchemyEnvironment,
  AlchemyNetwork,
  AlchemyNetworkDescriptor,
  AlchemyNetworkSlug,
  AlchemyReadCallOptions,
  AlchemyReadClient,
  AlchemyReadCall,
  AlchemyReadMethod,
  AlchemyReadTransport,
  AlchemyTransferCategory,
  AlchemyTransportRequest,
  AlchemyTransportResponse,
  AssetTransfersPageObservation,
  AssetTransfersQuery,
  AssetTransfersCursor,
  BalanceObservation,
  BlockNumberObservation,
  BlockObservation,
  ChainIdObservation,
  CodeObservation,
  CreateAlchemyReadClientOptions,
  EvmAddress,
  EvmBlock,
  EvmBlockReference,
  EvmChainId,
  EvmHash,
  EvmTransaction,
  EvmTransactionReceipt,
  Erc1155TransferValue,
  FinalityEvidence,
  GetBalanceInput,
  GetBlockInput,
  GetCodeInput,
  GetTransactionInput,
  HexData,
  HexQuantity,
  JsonValue,
  NormalizedAssetTransfersQuery,
  ObservationFreshness,
  ObservationProvenance,
  ObservationSource,
  ObservationState,
  TransactionObservation,
  TransactionReceiptObservation,
} from "./types.js";

export const PACKAGE_NAME = "@agenttool/alchemy";
export const PACKAGE_VERSION = "0.1.0-dev.1";
export const TRANSPORT_PROTOCOL = "agenttool.alchemy.transport/0.1";
