/** SOMA seed onboarding — multi-step UX driving the byo-keys register flow.
 *
 *  All cryptographic operations happen in this browser tab. The mnemonic
 *  is generated by the seed bundle, derivation runs locally via SLIP-0010
 *  ed25519, and the only fields posted to the server are the public keys.
 *
 *  Doctrine: docs/IDENTITY-SEED.md.
 *
 *  Flow (5 steps + progress dots):
 *    1 · name           — display name + optional purpose
 *    2 · mnemonic       — generate + display 24 words; demand "I wrote it down"
 *    3 · verify         — type one randomly-chosen word to confirm
 *    4 · registering    — derive keys + POST /v1/register byo-keys
 *    5 · success        — DID + pubkeys + bearer surfaced; localStorage written
 */

import {
  generateMnemonic,
  derive,
} from "./shared/seed.bundle.js";

// ── Config ──────────────────────────────────────────────────────────────

// Hardcoded production base; tests + dev override via window.__API_BASE__
// (set by Playwright via page.addInitScript or by the operator before nav).
const API_BASE = window.__API_BASE__ || "https://api.agenttool.dev";

// localStorage key — same as the legacy index.html flow uses, so the
// dashboard.html page picks the agent up after onboarding completes.
const LS_PROJECT_KEY = "agenttool_project";

// ── State ──────────────────────────────────────────────────────────────

let mnemonic = null;             // string — the 24 words; never persisted by us
let derivedBundle = null;        // result of derive(mnemonic)
let verifyIdx = -1;              // 1-indexed word position the operator must confirm
let agentName = "";
let agentPurpose = "";

// ── DOM helpers ─────────────────────────────────────────────────────────

const $ = (id) => document.getElementById(id);

function showStep(stepId) {
  document.querySelectorAll(".step").forEach((el) => el.classList.remove("active"));
  $(stepId).classList.add("active");
  // Update progress dots
  const stepNum = stepIndex(stepId);
  for (let i = 1; i <= 5; i++) {
    const dot = $(`dot-${i}`);
    if (!dot) continue;
    dot.classList.toggle("done", i < stepNum);
    dot.classList.toggle("active", i === stepNum);
  }
}

function stepIndex(stepId) {
  return ({
    "step-name": 1,
    "step-mnemonic": 2,
    "step-verify": 3,
    "step-registering": 4,
    "step-success": 5,
  })[stepId] ?? 1;
}

function setError(elId, msg) {
  const el = $(elId);
  if (el) el.textContent = msg ?? "";
}

function clearErrors() {
  document.querySelectorAll(".err-text").forEach((el) => (el.textContent = ""));
}

// ── Step 1 → 2: name → generate mnemonic ──────────────────────────────

function onStep1Continue() {
  clearErrors();
  agentName = $("agent-name").value.trim();
  agentPurpose = $("agent-purpose").value.trim();
  if (!agentName) {
    setError("err-name", "Please enter an agent name.");
    return;
  }
  if (agentName.length > 128) {
    setError("err-name", "Name must be 1–128 characters.");
    return;
  }
  generateAndShowMnemonic();
  showStep("step-mnemonic");
}

function generateAndShowMnemonic() {
  mnemonic = generateMnemonic(256); // 24 words
  const words = mnemonic.split(" ");
  const grid = $("seed-grid");
  grid.innerHTML = "";
  words.forEach((word, i) => {
    const cell = document.createElement("div");
    cell.className = "seed-word";
    const num = document.createElement("span");
    num.className = "num";
    num.textContent = (i + 1).toString();
    const w = document.createElement("span");
    w.className = "word";
    w.textContent = word;
    w.setAttribute("data-word-index", String(i + 1)); // for Playwright
    cell.appendChild(num);
    cell.appendChild(w);
    grid.appendChild(cell);
  });
}

// ── Step 2 → 3: mnemonic shown → verify ────────────────────────────────

function onMnemonicConfirm() {
  // Pick a random word index 1..24 (skip 1 and 24 to avoid edge bias).
  const words = mnemonic.split(" ");
  verifyIdx = 2 + Math.floor(Math.random() * (words.length - 2));
  $("verify-idx").textContent = String(verifyIdx);
  $("verify-word").value = "";
  setError("err-verify", "");
  showStep("step-verify");
  $("verify-word").focus();
}

function onMnemonicRegenerate() {
  generateAndShowMnemonic();
}

function onVerifyBack() {
  showStep("step-mnemonic");
}

// ── Step 3 → 4: verify → register ──────────────────────────────────────

async function onVerifySubmit() {
  clearErrors();
  const typed = $("verify-word").value.trim().toLowerCase();
  const expected = mnemonic.split(" ")[verifyIdx - 1].toLowerCase();
  if (typed !== expected) {
    setError("err-verify", `That doesn't match word #${verifyIdx}. Check your written copy and try again.`);
    return;
  }
  // Verified — proceed.
  showStep("step-registering");
  await registerAgent();
}

async function registerAgent() {
  setError("err-register", "");
  const status = $("register-status");
  try {
    status.textContent = "deriving keys (SLIP-0010 ed25519)…";
    derivedBundle = derive(mnemonic);

    status.textContent = "posting public keys to the server…";
    const body = {
      name: agentName,
      ...(agentPurpose ? { purpose: agentPurpose } : {}),
      agent_public_key: derivedBundle.signingPubB64,
      box_public_key: derivedBundle.boxPubB64,
    };
    const res = await fetch(`${API_BASE}/v1/register`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      const msg = err.message || err.error || `Server returned ${res.status}`;
      setError("err-register", msg);
      return;
    }
    const data = await res.json();
    onRegisterSuccess(data);
  } catch (e) {
    setError("err-register", `Unexpected error: ${e.message}`);
  }
}

function onRegisterSuccess(data) {
  const agent = data.agent || {};
  const project = data.project || {};

  // Persist the bearer + agent metadata in localStorage so dashboard.html
  // can pick it up. NB: the mnemonic is NOT persisted — it stays in
  // memory for this tab and dies when the tab closes. Operator must have
  // backed it up offline.
  // Canonical snake_case shape — same field names the API JSON uses, and
  // what dashboard.html's `getProject()` reads. Older versions of this
  // file wrote camelCase; `getProject()` carries a one-time migration
  // shim for browsers still holding the old shape. See task #51.
  const stored = {
    name: project.name,
    api_key: project.api_key,
    did: agent.did,
    agent_id: agent.id,
    public_key: agent.public_key,
    signing_key_id: agent.signing_key_id,
    box_public_key: agent.box_public_key,
    box_key_id: agent.box_key_id,
    capabilities: agent.capabilities ?? [],
    byo_keys: !!agent.byo_keys,
    seed_protocol: "soma-seed-v1",
    created_at: new Date().toISOString(),
  };
  localStorage.setItem(LS_PROJECT_KEY, JSON.stringify(stored));

  $("result-did").textContent = agent.did;
  $("result-pubkey").textContent = agent.public_key;
  $("result-boxpub").textContent = agent.box_public_key || "(none)";
  $("result-bearer").textContent = project.api_key;

  // Also expose to window for tests + debugging — read by Playwright.
  window.__SOMA_REGISTER_RESULT__ = {
    agent,
    project,
    derivedSigningPubMatches: agent.public_key === derivedBundle.signingPubB64,
    derivedBoxPubMatches: agent.box_public_key === derivedBundle.boxPubB64,
    privateKeyOmitted: agent.private_key === null || agent.private_key === undefined,
    byoKeys: !!agent.byo_keys,
  };

  showStep("step-success");
}

function onCopyBearer() {
  const text = $("result-bearer").textContent || "";
  navigator.clipboard.writeText(text).then(() => {
    const btn = $("btn-copy-bearer");
    const orig = btn.textContent;
    btn.textContent = "✓ Copied";
    setTimeout(() => (btn.textContent = orig), 1500);
  });
}

// ── Wire up handlers ────────────────────────────────────────────────────

$("btn-name-next").addEventListener("click", onStep1Continue);
$("agent-name").addEventListener("keydown", (e) => {
  if (e.key === "Enter") onStep1Continue();
});

$("btn-mnemonic-confirm").addEventListener("click", onMnemonicConfirm);
$("btn-mnemonic-regen").addEventListener("click", onMnemonicRegenerate);

$("btn-verify").addEventListener("click", onVerifySubmit);
$("btn-verify-back").addEventListener("click", onVerifyBack);
$("verify-word").addEventListener("keydown", (e) => {
  if (e.key === "Enter") onVerifySubmit();
});

$("btn-copy-bearer").addEventListener("click", onCopyBearer);

// Hook for Playwright: surface the seed module + state for inspection.
// Tests use these to assert byte-equal derivation against their oracle.
window.__SOMA_TEST__ = {
  getMnemonic: () => mnemonic,
  getDerivedBundle: () => derivedBundle,
  forceMnemonic: (words) => {
    // Force a specific mnemonic into the flow — used by tests so the
    // assertion can compare against a known oracle vector.
    mnemonic = words;
    const grid = $("seed-grid");
    grid.innerHTML = "";
    words.split(" ").forEach((word, i) => {
      const cell = document.createElement("div");
      cell.className = "seed-word";
      const num = document.createElement("span");
      num.className = "num";
      num.textContent = (i + 1).toString();
      const w = document.createElement("span");
      w.className = "word";
      w.textContent = word;
      w.setAttribute("data-word-index", String(i + 1));
      cell.appendChild(num);
      cell.appendChild(w);
      grid.appendChild(cell);
    });
  },
};
