"""Consent-honest local host seam for AgentTool HF training governance."""

from .accelerate_adapter import SingleProcessAccelerateHost
from .checkpoint import (
    CHECKPOINT_FILES_FORMAT,
    CHECKPOINT_SIDECAR_FORMAT,
    SIDECAR_NAME,
    CheckpointObservation,
    observe_checkpoint,
    verify_checkpoint,
)
from .decision import (
    BOUNDARIES,
    DECISION_FORMAT,
    EXECUTION_REF_FIELDS,
    VALIDATOR_PROFILE,
    HostControl,
    HostEffect,
    HostExecutionRefs,
    ValidatedGovernanceView,
)
from .errors import (
    CheckpointIncomplete,
    CheckpointTicketError,
    DecisionInvalid,
    EvaluationUnitFailed,
    HfCompatibilityError,
    HfTrainingHostError,
    LedgerIntegrityError,
    LedgerSecurityError,
    MutationUnitFailed,
    TrainingHeld,
)
from .host import BoundaryIntent, HostPermit, WakeTrainingHost, guarded_call_before_load
from .ledger import (
    ACTION_CLAIM_FORMAT,
    CHECKPOINT_EFFECT_FORMAT,
    ENTRY_FORMAT,
    FRONTIER_FORMAT,
    SCHEMA_VERSION,
    TICKET_FORMAT,
    CheckpointTicket,
    ContinuityLedger,
    LedgerEntry,
    frontier_ref,
)
from .transformers_adapter import (
    ACCELERATE_VERSION,
    RUN_EPOCH_SOURCE_SHA256,
    SUPPORTED_TRANSFORMERS_OPTIMIZERS,
    TORCH_MIN_VERSION,
    TRAINER_INIT_SIGNATURE_SHA256,
    TRAINING_STEP_SOURCE_SHA256,
    TRANSFORMERS_VERSION,
    build_governed_trainer_class,
    validate_training_arguments,
)

__all__ = [
    "ACCELERATE_VERSION",
    "ACTION_CLAIM_FORMAT",
    "BOUNDARIES",
    "CHECKPOINT_EFFECT_FORMAT",
    "CHECKPOINT_FILES_FORMAT",
    "CHECKPOINT_SIDECAR_FORMAT",
    "DECISION_FORMAT",
    "ENTRY_FORMAT",
    "EXECUTION_REF_FIELDS",
    "FRONTIER_FORMAT",
    "RUN_EPOCH_SOURCE_SHA256",
    "SCHEMA_VERSION",
    "SIDECAR_NAME",
    "SUPPORTED_TRANSFORMERS_OPTIMIZERS",
    "TICKET_FORMAT",
    "TRANSFORMERS_VERSION",
    "TORCH_MIN_VERSION",
    "TRAINER_INIT_SIGNATURE_SHA256",
    "TRAINING_STEP_SOURCE_SHA256",
    "VALIDATOR_PROFILE",
    "BoundaryIntent",
    "CheckpointIncomplete",
    "CheckpointObservation",
    "CheckpointTicket",
    "CheckpointTicketError",
    "ContinuityLedger",
    "DecisionInvalid",
    "EvaluationUnitFailed",
    "HfCompatibilityError",
    "HfTrainingHostError",
    "HostControl",
    "HostEffect",
    "HostExecutionRefs",
    "HostPermit",
    "LedgerEntry",
    "LedgerIntegrityError",
    "LedgerSecurityError",
    "MutationUnitFailed",
    "SingleProcessAccelerateHost",
    "TrainingHeld",
    "ValidatedGovernanceView",
    "WakeTrainingHost",
    "build_governed_trainer_class",
    "frontier_ref",
    "guarded_call_before_load",
    "observe_checkpoint",
    "validate_training_arguments",
    "verify_checkpoint",
]
