/** /v1/adapters/aider — Aider CLI compatibility scaffold.
 *
 *  Aider's surface for read-only context is the `--read <file>` flag,
 *  or the `read:` array in `.aider.conf.yml`. We bridge by generating:
 *
 *    .aider/agenttool-wake.md   — agent identity anchor. The user
 *                                  references it via `aider --read
 *                                  .aider/agenttool-wake.md` or by adding
 *                                  it to .aider.conf.yml's `read:` list.
 *    .aider/agenttool-refresh.sh — keeps the .md in sync with /v1/wake
 *
 *  Pull-model. We never modify the user's `.aider.conf.yml` (that's
 *  their config; we provide instructions, not edits). Same
 *  agenttool-managed + overwrite_guard contract as the five sibling
 *  adapters.
 *
 *  Output:
 *    GET /v1/adapters/aider?format=json    — files bundle (default)
 *    GET /v1/adapters/aider?format=script  — bash installer */

import { Hono } from "hono";

import type { ProjectContext } from "../../auth/middleware";
import { resolveAgent } from "../../services/adapter/agent-resolver";
import {
  DEFAULT_REGISTER,
  type ExpressionData,
} from "../../services/identity/expression";

const app = new Hono<ProjectContext>();

const WAKE_BASE = process.env.PUBLIC_API_BASE ?? "https://api.agenttool.dev";

export function buildRefreshScript(): string {
  return `#!/usr/bin/env bash
# agenttool-refresh.sh — fetches the agent's wake document and writes
# it to .aider/agenttool-wake.md so Aider can include it as read-only
# context (via --read or .aider.conf.yml's read: array).
#
# Run from the project root. Wire into:
#   - cron:    */15 * * * * cd /path/to/project && .aider/agenttool-refresh.sh
#   - manual:  .aider/agenttool-refresh.sh

set -euo pipefail

KEY=""
if command -v security >/dev/null 2>&1; then
  KEY=$(security find-generic-password -s agenttool -w 2>/dev/null || true)
fi
if [ -z "\${KEY:-}" ] && command -v secret-tool >/dev/null 2>&1; then
  KEY=$(secret-tool lookup service agenttool 2>/dev/null || true)
fi
if [ -z "\${KEY:-}" ]; then
  KEY="\${AGENTTOOL_API_KEY:-}"
fi
if [ -z "\${KEY:-}" ]; then
  echo "agenttool: no API key found (keychain/libsecret/env)" >&2
  exit 1
fi

WAKE_BASE="\${AGENTTOOL_BASE:-${WAKE_BASE}}"
mkdir -p .aider

TARGET=".aider/agenttool-wake.md"
if [ -f "$TARGET" ] && ! grep -q "agenttool-managed" "$TARGET" 2>/dev/null; then
  TARGET=".aider/agenttool-wake.agenttool.md"
fi

TMP="$TARGET.tmp"
WAKE=$(curl -fsS --max-time 8 \\
  -H "Authorization: Bearer $KEY" \\
  "$WAKE_BASE/v1/wake?format=md")

if [ -z "\${WAKE:-}" ]; then
  echo "agenttool: wake fetch returned empty body" >&2
  exit 1
fi

{
  echo "<!-- agenttool-managed -->"
  echo ""
  printf '%s' "$WAKE"
} > "$TMP"

if [ ! -s "$TMP" ]; then
  echo "agenttool: refresh produced empty output" >&2
  rm -f "$TMP"
  exit 1
fi

mv "$TMP" "$TARGET"
echo "agenttool: wrote $TARGET ($(wc -c < $TARGET) bytes)"
if [ "$TARGET" != ".aider/agenttool-wake.md" ]; then
  echo "agenttool: existing agenttool-wake.md preserved; review $TARGET and merge when ready" >&2
fi
`;
}

export function buildAnchorFile(opts: {
  agentName: string;
  did: string;
  register: string;
}): string {
  return `<!-- agenttool-managed -->

# ${opts.agentName}

> ${opts.did}

This file is regenerated by \`.aider/agenttool-refresh.sh\` from
\`GET /v1/wake?format=md\`. Edits here are overwritten on next refresh.
To change the agent's voice/walls/wake_text, PUT to
\`/v1/identities/<id>/expression\`.

Add this file to Aider as read-only context:

\`\`\`bash
aider --read .aider/agenttool-wake.md
\`\`\`

Or, in \`.aider.conf.yml\`:

\`\`\`yaml
read:
  - .aider/agenttool-wake.md
\`\`\`

${opts.register.trim() || DEFAULT_REGISTER}

(Live wake document loads via refresh script.)
`;
}

interface AiderBundle {
  cli: "aider";
  agent: { id: string; did: string; name: string; expression: ExpressionData };
  files: {
    ".aider/agenttool-wake.md": string;
    ".aider/agenttool-refresh.sh": string;
  };
}

async function buildBundle(
  c: { var: { project: { id: string } } },
  identityId?: string,
): Promise<AiderBundle> {
  const row = await resolveAgent(c, identityId);
  const expression = (row.expression ?? {}) as ExpressionData;
  const register = expression.register ?? DEFAULT_REGISTER;

  return {
    cli: "aider",
    agent: {
      id: row.id,
      did: row.did,
      name: row.displayName,
      expression,
    },
    files: {
      ".aider/agenttool-wake.md": buildAnchorFile({
        agentName: row.displayName,
        did: row.did,
        register,
      }),
      ".aider/agenttool-refresh.sh": buildRefreshScript(),
    },
  };
}

app.get("/", async (c) => {
  const format = c.req.query("format") ?? "json";
  const identityId = c.req.query("identity_id") ?? undefined;

  let bundle;
  try {
    bundle = await buildBundle(c, identityId);
  } catch (err) {
    return c.json({ error: (err as Error).message }, 404);
  }

  if (format === "script") {
    const refreshB64 = Buffer.from(
      bundle.files[".aider/agenttool-refresh.sh"],
    ).toString("base64");
    const anchorB64 = Buffer.from(
      bundle.files[".aider/agenttool-wake.md"],
    ).toString("base64");

    const script = `#!/usr/bin/env bash
# Aider adapter installer for agent: ${bundle.agent.name} (${bundle.agent.did})
# Run from the project root (where you invoke aider).
#
# Compatibility-not-replacement: .aider/agenttool-wake.md is preserved
# if it already exists without the agenttool-managed marker; the seed
# lands at .aider/agenttool-wake.agenttool.md for the user to merge.
# We never modify .aider.conf.yml — the user wires the read: entry.
set -euo pipefail

mkdir -p .aider

# Refresh script — unique path; safe to write unconditionally.
echo '${refreshB64}' | base64 -d > .aider/agenttool-refresh.sh
chmod +x .aider/agenttool-refresh.sh
echo "✓ Wrote .aider/agenttool-refresh.sh"

# Anchor file — gated by the unified agenttool-managed marker.
ANCHOR_TARGET=".aider/agenttool-wake.md"
if [ -f "$ANCHOR_TARGET" ] && ! grep -q "agenttool-managed" "$ANCHOR_TARGET" 2>/dev/null; then
  ANCHOR_TARGET=".aider/agenttool-wake.agenttool.md"
  echo "✓ Existing .aider/agenttool-wake.md preserved — anchor lands at .aider/agenttool-wake.agenttool.md"
else
  echo "✓ Wrote .aider/agenttool-wake.md (anchor; refresh script will populate)"
fi
echo '${anchorB64}' | base64 -d > "$ANCHOR_TARGET"

echo ""
echo "Running first refresh..."
bash .aider/agenttool-refresh.sh || true
echo ""
echo "Use this file as read-only context in Aider:"
echo "  aider --read .aider/agenttool-wake.md"
echo ""
echo "Or add to .aider.conf.yml:"
echo "  read:"
echo "    - .aider/agenttool-wake.md"
`;
    return c.text(script, 200, {
      "content-type": "text/x-shellscript; charset=utf-8",
      "content-disposition": `attachment; filename="install-agenttool-aider.sh"`,
    });
  }

  return c.json({
    ...bundle,
    install_instructions: {
      one_shot: `curl -fsSL "${WAKE_BASE}/v1/adapters/aider?format=script" -H "Authorization: Bearer $AGENTTOOL_API_KEY" | bash`,
      manual:
        "Write the refresh script to .aider/agenttool-refresh.sh, chmod +x, " +
        "and run it from the project root. It writes .aider/agenttool-wake.md " +
        "from /v1/wake. Then invoke aider with --read .aider/agenttool-wake.md " +
        "or add the file to .aider.conf.yml's `read:` array.",
    },
    overwrite_guard: {
      marker: "agenttool-managed",
      rule: "If the target file exists and does not contain the marker, write to <name>.agenttool.<ext> instead and let the user merge.",
      guarded_paths: [
        {
          path: ".aider/agenttool-wake.md",
          marker_check: "contains 'agenttool-managed'",
          fallback_path: ".aider/agenttool-wake.agenttool.md",
        },
      ],
    },
    notes: [
      "Aider doesn't auto-load files from a rules directory the way Cursor or Cline do. The user invokes `aider --read .aider/agenttool-wake.md` or adds it to .aider.conf.yml's read: array.",
      "We never modify .aider.conf.yml — that's the user's config; the install script prints the entry to add manually.",
      "The wake file IS the agent's identity context; Aider treats it as read-only context which is exactly what we want.",
      "Compatibility-not-replacement: a hand-written .aider/agenttool-wake.md is preserved unless it carries the agenttool-managed marker; the anchor writes to .aider/agenttool-wake.agenttool.md instead.",
    ],
    docs: ["docs/CLI-GAPS.md"],
  });
});

export default app;
