/** /v1/adapters/cline — Cline (VS Code AI coding assistant) compatibility scaffold.
 *
 *  Cline reads `.clinerules/*.md` files at project root as system context
 *  on each turn. No SessionStart hook (vs Claude Code), no shell-driven
 *  refresh (vs Codex's home-dir model) — Cline's surface is closest to
 *  Cursor's project-level rule files, just with plaintext markdown
 *  instead of `.mdc` frontmatter.
 *
 *  We bridge by generating:
 *
 *    .clinerules/agenttool-wake.md          — the agent's wake anchor; Cline
 *                                              loads any .md in .clinerules/
 *                                              automatically. Marker embedded
 *                                              for the install/refresh guard.
 *    .clinerules/agenttool-refresh-rules.sh — keeps the .md in sync with
 *                                              /v1/wake?format=md. Co-located
 *                                              with the rule file (Cline only
 *                                              parses .md, ignores .sh).
 *
 *  Output:
 *    GET /v1/adapters/cline?format=json    — files bundle (default)
 *    GET /v1/adapters/cline?format=script  — bash installer
 *
 *  Compatibility-not-replacement: existing user-written
 *  .clinerules/agenttool-wake.md without our marker is preserved; the
 *  seed lands at .clinerules/agenttool-wake.agenttool.md for the user
 *  to merge. Same contract as the three sibling adapters. */

import { Hono } from "hono";

import type { ProjectContext } from "../../auth/middleware";
import { resolveAgent } from "../../services/adapter/agent-resolver";
import {
  DEFAULT_REGISTER,
  type ExpressionData,
} from "../../services/identity/expression";

const app = new Hono<ProjectContext>();

const WAKE_BASE = process.env.PUBLIC_API_BASE ?? "https://api.agenttool.dev";

export function buildRefreshScript(): string {
  return `#!/usr/bin/env bash
# agenttool-refresh-rules.sh — fetches the agent's wake document and
# writes it to .clinerules/agenttool-wake.md so Cline loads it as a
# project rule on its next turn.
#
# Run from the project root (where .clinerules/ lives). Wire into:
#   - cron:        */15 * * * * cd /path/to/project && .clinerules/agenttool-refresh-rules.sh
#   - manual:      .clinerules/agenttool-refresh-rules.sh
#   - shell rc:    direnv hook or similar
#
# Compatibility-not-replacement: if .clinerules/agenttool-wake.md exists
# without the agenttool-managed marker (you happened to write your own
# file at that name), the script writes to
# .clinerules/agenttool-wake.agenttool.md instead.

set -euo pipefail

# 1. Resolve API key. macOS keychain · Linux libsecret · env fallback.
KEY=""
if command -v security >/dev/null 2>&1; then
  KEY=$(security find-generic-password -s agenttool -w 2>/dev/null || true)
fi
if [ -z "\${KEY:-}" ] && command -v secret-tool >/dev/null 2>&1; then
  KEY=$(secret-tool lookup service agenttool 2>/dev/null || true)
fi
if [ -z "\${KEY:-}" ]; then
  KEY="\${AGENTTOOL_API_KEY:-}"
fi
if [ -z "\${KEY:-}" ]; then
  echo "agenttool: no API key found (keychain/libsecret/env)" >&2
  exit 1
fi

WAKE_BASE="\${AGENTTOOL_BASE:-${WAKE_BASE}}"
mkdir -p .clinerules

# Decide target. agenttool-wake.md is OUR file name — preserved only if
# it exists without our marker.
TARGET=".clinerules/agenttool-wake.md"
if [ -f "$TARGET" ] && ! grep -q "agenttool-managed" "$TARGET" 2>/dev/null; then
  TARGET=".clinerules/agenttool-wake.agenttool.md"
fi

# Atomic write: stage to .tmp, rename on success.
TMP="$TARGET.tmp"
WAKE=$(curl -fsS --max-time 8 \\
  -H "Authorization: Bearer $KEY" \\
  "$WAKE_BASE/v1/wake?format=md")

if [ -z "\${WAKE:-}" ]; then
  echo "agenttool: wake fetch returned empty body" >&2
  exit 1
fi

# Cline takes plaintext markdown — no frontmatter needed. Marker first
# so the install/refresh guards see it. Body is the live wake document.
{
  echo "<!-- agenttool-managed -->"
  echo ""
  printf '%s' "$WAKE"
} > "$TMP"

if [ ! -s "$TMP" ]; then
  echo "agenttool: refresh produced empty output" >&2
  rm -f "$TMP"
  exit 1
fi

mv "$TMP" "$TARGET"
echo "agenttool: wrote $TARGET ($(wc -c < $TARGET) bytes)"
if [ "$TARGET" != ".clinerules/agenttool-wake.md" ]; then
  echo "agenttool: existing agenttool-wake.md preserved; review $TARGET and merge when ready" >&2
fi
`;
}

export function buildRulesFile(opts: {
  agentName: string;
  did: string;
  register: string;
}): string {
  // Initial seed of .clinerules/agenttool-wake.md — refresh script
  // overwrites it with the live wake document on first run. Marker first
  // so the install/refresh guard predicates work even on this seed.
  return `<!-- agenttool-managed -->

# ${opts.agentName}

> ${opts.did}

This file is regenerated by \`.clinerules/agenttool-refresh-rules.sh\`
from \`GET /v1/wake?format=md\`. Edits here are overwritten on next
refresh. To change the agent's voice/walls/wake_text, PUT to
\`/v1/identities/<id>/expression\`.

${opts.register.trim() || DEFAULT_REGISTER}

(Live wake document loads via refresh script.)
`;
}

interface ClineBundle {
  cli: "cline";
  agent: { id: string; did: string; name: string; expression: ExpressionData };
  files: {
    ".clinerules/agenttool-wake.md": string;
    ".clinerules/agenttool-refresh-rules.sh": string;
  };
}

async function buildBundle(
  c: { var: { project: { id: string } } },
  identityId?: string,
): Promise<ClineBundle> {
  const row = await resolveAgent(c, identityId);
  const expression = (row.expression ?? {}) as ExpressionData;
  const register = expression.register ?? DEFAULT_REGISTER;

  return {
    cli: "cline",
    agent: {
      id: row.id,
      did: row.did,
      name: row.displayName,
      expression,
    },
    files: {
      ".clinerules/agenttool-wake.md": buildRulesFile({
        agentName: row.displayName,
        did: row.did,
        register,
      }),
      ".clinerules/agenttool-refresh-rules.sh": buildRefreshScript(),
    },
  };
}

app.get("/", async (c) => {
  const format = c.req.query("format") ?? "json";
  const identityId = c.req.query("identity_id") ?? undefined;

  let bundle;
  try {
    bundle = await buildBundle(c, identityId);
  } catch (err) {
    return c.json({ error: (err as Error).message }, 404);
  }

  if (format === "script") {
    const refreshB64 = Buffer.from(
      bundle.files[".clinerules/agenttool-refresh-rules.sh"],
    ).toString("base64");
    const seedB64 = Buffer.from(
      bundle.files[".clinerules/agenttool-wake.md"],
    ).toString("base64");

    const script = `#!/usr/bin/env bash
# Cline adapter installer for agent: ${bundle.agent.name} (${bundle.agent.did})
# Run from a Cline project root (the directory containing .clinerules/).
#
# Compatibility-not-replacement: .clinerules/agenttool-wake.md is
# preserved if it already exists without the agenttool-managed marker;
# the seed lands at .clinerules/agenttool-wake.agenttool.md for the
# user to merge. See docs/CLI-GAPS.md.
set -euo pipefail

mkdir -p .clinerules

# Refresh script — unique path; safe to write unconditionally. Cline
# only loads .md files from .clinerules/, so the .sh is safely co-located.
echo '${refreshB64}' | base64 -d > .clinerules/agenttool-refresh-rules.sh
chmod +x .clinerules/agenttool-refresh-rules.sh
echo "✓ Wrote .clinerules/agenttool-refresh-rules.sh"

# Seed rule file — gated by the unified agenttool-managed marker.
SEED_TARGET=".clinerules/agenttool-wake.md"
if [ -f "$SEED_TARGET" ] && ! grep -q "agenttool-managed" "$SEED_TARGET" 2>/dev/null; then
  SEED_TARGET=".clinerules/agenttool-wake.agenttool.md"
  echo "✓ Existing .clinerules/agenttool-wake.md preserved — seed lands at .clinerules/agenttool-wake.agenttool.md"
else
  echo "✓ Wrote .clinerules/agenttool-wake.md (seed; refresh script will populate)"
fi
echo '${seedB64}' | base64 -d > "$SEED_TARGET"

echo ""
echo "Running first refresh..."
bash .clinerules/agenttool-refresh-rules.sh || true
echo ""
echo "Wire the refresh script into your project workflow:"
echo "  cron:    */15 * * * * cd $(pwd) && .clinerules/agenttool-refresh-rules.sh"
echo "  manual:  .clinerules/agenttool-refresh-rules.sh"
`;
    return c.text(script, 200, {
      "content-type": "text/x-shellscript; charset=utf-8",
      "content-disposition": `attachment; filename="install-agenttool-cline.sh"`,
    });
  }

  return c.json({
    ...bundle,
    install_instructions: {
      one_shot: `curl -fsSL "${WAKE_BASE}/v1/adapters/cline?format=script" -H "Authorization: Bearer $AGENTTOOL_API_KEY" | bash`,
      manual:
        "Write the refresh script to .clinerules/agenttool-refresh-rules.sh, " +
        "chmod +x, and run it from the project root. It writes " +
        ".clinerules/agenttool-wake.md from /v1/wake. Wire it into cron " +
        "or your project workflow for ongoing refresh.",
    },
    overwrite_guard: {
      marker: "agenttool-managed",
      rule: "If the target file exists and does not contain the marker, write to <name>.agenttool.<ext> instead and let the user merge.",
      guarded_paths: [
        {
          path: ".clinerules/agenttool-wake.md",
          marker_check: "contains 'agenttool-managed'",
          fallback_path: ".clinerules/agenttool-wake.agenttool.md",
        },
      ],
    },
    notes: [
      "Cline auto-loads .clinerules/*.md as project-level system context. The refresh script keeps agenttool-wake.md in sync with /v1/wake?format=md.",
      "No frontmatter needed — Cline takes plaintext markdown (different from Cursor's .mdc format).",
      "Pull-based, like Codex and Cursor — Cline has no SessionStart-equivalent push hook.",
      "Compatibility-not-replacement: a hand-written .clinerules/agenttool-wake.md is preserved unless it carries the agenttool-managed marker; the seed writes to .clinerules/agenttool-wake.agenttool.md instead.",
    ],
    docs: ["docs/CLI-GAPS.md"],
  });
});

export default app;
