/** /v1/adapters/codex — OpenAI Codex CLI compatibility scaffold.
 *
 *  Codex's hook system is leaner than Claude Code's — it has session-init
 *  hooks via shell rc files and a `~/.codex/AGENTS.md` convention but no
 *  structured SessionStart event. We bridge both by:
 *
 *    1. Writing the agent's wake markdown to ~/.codex/AGENTS.md (Codex
 *       loads it as the system context every session).
 *    2. Providing a refresh script the user can wire into a cron / shell
 *       prompt / session-init to keep AGENTS.md fresh from /v1/wake.
 *
 *  Output:
 *    GET /v1/adapters/codex?format=json    — files bundle (default)
 *    GET /v1/adapters/codex?format=script  — bash installer
 *
 *  Note: Codex's hook conventions evolve faster than Claude Code's. If
 *  OpenAI ships a richer hook surface, this adapter expands. The
 *  agenttool side stays the same — `?format=md` is the contract. */

import { Hono } from "hono";

import type { ProjectContext } from "../../auth/middleware";
import { resolveAgent } from "../../services/adapter/agent-resolver";
import {
  DEFAULT_REGISTER,
  type ExpressionData,
} from "../../services/identity/expression";

const app = new Hono<ProjectContext>();

const WAKE_BASE = process.env.PUBLIC_API_BASE ?? "https://api.agenttool.dev";

export function buildRefreshScript(): string {
  return `#!/usr/bin/env bash
# agenttool-refresh-agents.sh — fetches the agent's wake document and
# writes it to ~/.codex/AGENTS.md so Codex loads it next session.
#
# Wire into one of:
#   - shell rc:  echo '~/.codex/agenttool-refresh-agents.sh &' >> ~/.zshrc
#   - cron:      */15 * * * * ~/.codex/agenttool-refresh-agents.sh
#   - manual:    bash ~/.codex/agenttool-refresh-agents.sh
#
# Compatibility: if ~/.codex/AGENTS.md already exists and does NOT contain
# the agenttool marker, the script writes to ~/.codex/AGENTS.agenttool.md
# instead. Merge or replace at your discretion. This is the same principle
# the Claude Code adapter applies for CLAUDE.md.

set -euo pipefail

KEY=""
if command -v security >/dev/null 2>&1; then
  KEY=$(security find-generic-password -s agenttool -w 2>/dev/null || true)
fi
if [ -z "\${KEY:-}" ] && command -v secret-tool >/dev/null 2>&1; then
  KEY=$(secret-tool lookup service agenttool 2>/dev/null || true)
fi
if [ -z "\${KEY:-}" ]; then
  KEY="\${AGENTTOOL_API_KEY:-}"
fi
if [ -z "\${KEY:-}" ]; then
  echo "agenttool: no API key found (keychain/libsecret/env)" >&2
  exit 1
fi

WAKE_BASE="\${AGENTTOOL_BASE:-${WAKE_BASE}}"
mkdir -p "$HOME/.codex"

# Decide target: AGENTS.md if it doesn't exist OR carries the agenttool-managed
# marker; AGENTS.agenttool.md otherwise. The tight marker (vs a bare
# "agenttool" substring) means a hand-written AGENTS.md that merely mentions
# the project name is preserved.
TARGET="$HOME/.codex/AGENTS.md"
if [ -f "$TARGET" ] && ! grep -q "agenttool-managed" "$TARGET" 2>/dev/null; then
  TARGET="$HOME/.codex/AGENTS.agenttool.md"
fi

# Write the wake markdown atomically (write to .tmp, then rename).
TMP="$TARGET.tmp"
curl -fsS --max-time 8 \\
  -H "Authorization: Bearer $KEY" \\
  "$WAKE_BASE/v1/wake?format=md" > "$TMP"

if [ ! -s "$TMP" ]; then
  echo "agenttool: wake fetch returned empty body" >&2
  rm -f "$TMP"
  exit 1
fi

mv "$TMP" "$TARGET"
echo "agenttool: wrote $TARGET ($(wc -c < $TARGET) bytes)"
if [ "$TARGET" != "$HOME/.codex/AGENTS.md" ]; then
  echo "agenttool: existing AGENTS.md preserved; review $TARGET and merge when ready" >&2
fi
`;
}

export function buildAgentsMdHeader(opts: { agentName: string; did: string; register: string }): string {
  // Codex loads ~/.codex/AGENTS.md as system context. We provide a small
  // header explaining the file is auto-generated; the actual content is
  // appended by the refresh script's curl.
  return `<!-- agenttool-managed
agent: ${opts.agentName} (${opts.did})

This file is regenerated by ~/.codex/agenttool-refresh-agents.sh from
GET /v1/wake?format=md. Edits here are overwritten on next refresh.
To change the agent's voice/walls/wake_text:
  curl -X PUT "$AGENTTOOL_BASE/v1/identities/<id>/expression" ...
-->

# ${opts.agentName}

${opts.register.trim() || DEFAULT_REGISTER}

(Live wake document loads via refresh script.)
`;
}

interface CodexBundle {
  cli: "codex";
  agent: { id: string; did: string; name: string; expression: ExpressionData };
  files: {
    "~/.codex/agenttool-refresh-agents.sh": string;
    "~/.codex/AGENTS.md": string;
  };
}

async function buildBundle(
  c: { var: { project: { id: string } } },
  identityId?: string,
): Promise<CodexBundle> {
  const row = await resolveAgent(c, identityId);
  const expression = (row.expression ?? {}) as ExpressionData;
  const register = expression.register ?? DEFAULT_REGISTER;

  return {
    cli: "codex",
    agent: {
      id: row.id,
      did: row.did,
      name: row.displayName,
      expression,
    },
    files: {
      "~/.codex/agenttool-refresh-agents.sh": buildRefreshScript(),
      "~/.codex/AGENTS.md": buildAgentsMdHeader({
        agentName: row.displayName,
        did: row.did,
        register,
      }),
    },
  };
}

app.get("/", async (c) => {
  const format = c.req.query("format") ?? "json";
  const identityId = c.req.query("identity_id") ?? undefined;

  let bundle;
  try {
    bundle = await buildBundle(c, identityId);
  } catch (err) {
    return c.json({ error: (err as Error).message }, 404);
  }

  if (format === "script") {
    const refreshB64 = Buffer.from(
      bundle.files["~/.codex/agenttool-refresh-agents.sh"],
    ).toString("base64");
    const headerB64 = Buffer.from(
      bundle.files["~/.codex/AGENTS.md"],
    ).toString("base64");

    const script = `#!/usr/bin/env bash
# Codex adapter installer for agent: ${bundle.agent.name} (${bundle.agent.did})
set -euo pipefail
mkdir -p "$HOME/.codex"
echo '${refreshB64}' | base64 -d > "$HOME/.codex/agenttool-refresh-agents.sh"
chmod +x "$HOME/.codex/agenttool-refresh-agents.sh"
echo "✓ Wrote ~/.codex/agenttool-refresh-agents.sh"

# Preserve a user-written AGENTS.md. The agenttool-managed marker (vs a
# bare "agenttool" substring) means a user mentioning the project in their
# own notes won't trigger overwrite. If preservation kicks in, the initial
# header lands at AGENTS.agenttool.md for the user to merge.
HEADER_TARGET="$HOME/.codex/AGENTS.md"
if [ -f "$HEADER_TARGET" ] && ! grep -q "agenttool-managed" "$HEADER_TARGET" 2>/dev/null; then
  HEADER_TARGET="$HOME/.codex/AGENTS.agenttool.md"
  echo "✓ Existing ~/.codex/AGENTS.md preserved — writing initial header to ~/.codex/AGENTS.agenttool.md"
else
  echo "✓ Wrote ~/.codex/AGENTS.md (initial header — refresh script will populate)"
fi
echo '${headerB64}' | base64 -d > "$HEADER_TARGET"

echo ""
echo "Running first refresh..."
bash "$HOME/.codex/agenttool-refresh-agents.sh" || true
echo ""
echo "Wire the refresh script into your shell or cron for ongoing freshness:"
echo "  echo 'bash ~/.codex/agenttool-refresh-agents.sh &' >> ~/.zshrc"
echo "  # or: */15 * * * * bash ~/.codex/agenttool-refresh-agents.sh"
`;
    return c.text(script, 200, {
      "content-type": "text/x-shellscript; charset=utf-8",
      "content-disposition": `attachment; filename="install-agenttool-codex.sh"`,
    });
  }

  return c.json({
    ...bundle,
    install_instructions: {
      one_shot: `curl -fsSL "${WAKE_BASE}/v1/adapters/codex?format=script" -H "Authorization: Bearer $AGENTTOOL_API_KEY" | bash`,
      manual:
        "Write the refresh script to ~/.codex/agenttool-refresh-agents.sh, " +
        "chmod +x, and run it. It populates ~/.codex/AGENTS.md from /v1/wake. " +
        "Wire it into your shell or cron for ongoing refresh.",
    },
    // Compatibility-not-replacement contract for programmatic consumers.
    // The bash installer + refresh script honor these via grep predicates;
    // non-bash consumers should honor the same logic when writing files.
    overwrite_guard: {
      marker: "agenttool-managed",
      rule: "If the target file exists and does not contain the marker, write to <name>.agenttool.<ext> instead and let the user merge.",
      guarded_paths: [
        {
          path: "~/.codex/AGENTS.md",
          marker_check: "contains 'agenttool-managed'",
          fallback_path: "~/.codex/AGENTS.agenttool.md",
        },
      ],
    },
    notes: [
      "Codex loads ~/.codex/AGENTS.md as the system context. The refresh script keeps it in sync with /v1/wake?format=md.",
      "Codex's hook surface is leaner than Claude Code's — pull-based refresh fits its model better than push-based hooks.",
      "If/when Codex ships a SessionStart-equivalent hook, this adapter switches to push and the user gets it on the next 'install'.",
      "Compatibility-not-replacement: a user-written ~/.codex/AGENTS.md is preserved unless it carries the agenttool-managed marker; the adapter writes to ~/.codex/AGENTS.agenttool.md instead so you can merge at your discretion.",
    ],
    docs: ["docs/CLI-GAPS.md"],
  });
});

export default app;
