/** /v1/adapters/replit — Replit AI compatibility scaffold.
 *
 *  Substrate-honest note up front: Replit AI's session-context surface
 *  is the least standardized of the six adapters. Replit reads the
 *  workspace files but doesn't document a specific "load this as system
 *  prompt" convention like Cursor's `.cursor/rules/` or Cline's
 *  `.clinerules/`. Community usage of `replit.md` as a project-level
 *  context anchor is informal but stable enough to lean on.
 *
 *  We bridge by generating:
 *
 *    replit.md                          — agent identity anchor at project
 *                                          root. Community convention; the
 *                                          user references it from their
 *                                          AI session if Replit doesn't
 *                                          surface it automatically.
 *    .replit-agenttool/refresh.sh       — keeps replit.md in sync with
 *                                          /v1/wake?format=md (own subdir
 *                                          to avoid touching .replit/).
 *
 *  The .replit/ directory is reserved for Replit's TOML config — we
 *  never touch it. .replit-agenttool/ is our own namespace.
 *
 *  Output:
 *    GET /v1/adapters/replit?format=json    — files bundle (default)
 *    GET /v1/adapters/replit?format=script  — bash installer */

import { Hono } from "hono";

import type { ProjectContext } from "../../auth/middleware";
import { resolveAgent } from "../../services/adapter/agent-resolver";
import {
  DEFAULT_REGISTER,
  type ExpressionData,
} from "../../services/identity/expression";

const app = new Hono<ProjectContext>();

const WAKE_BASE = process.env.PUBLIC_API_BASE ?? "https://api.agenttool.dev";

export function buildRefreshScript(): string {
  return `#!/usr/bin/env bash
# agenttool-refresh.sh — fetches the agent's wake document and writes
# it to replit.md at the project root so Replit's workspace surfaces
# it as project context.
#
# Run from the project root. Wire into:
#   - cron:    */15 * * * * cd /path/to/project && .replit-agenttool/refresh.sh
#   - manual:  .replit-agenttool/refresh.sh
#
# Compatibility-not-replacement: if replit.md exists without the
# agenttool-managed marker (the user wrote their own), the script
# writes to replit.agenttool.md instead.

set -euo pipefail

KEY=""
if command -v security >/dev/null 2>&1; then
  KEY=$(security find-generic-password -s agenttool -w 2>/dev/null || true)
fi
if [ -z "\${KEY:-}" ] && command -v secret-tool >/dev/null 2>&1; then
  KEY=$(secret-tool lookup service agenttool 2>/dev/null || true)
fi
if [ -z "\${KEY:-}" ]; then
  KEY="\${AGENTTOOL_API_KEY:-}"
fi
if [ -z "\${KEY:-}" ]; then
  echo "agenttool: no API key found (keychain/libsecret/env)" >&2
  exit 1
fi

WAKE_BASE="\${AGENTTOOL_BASE:-${WAKE_BASE}}"

TARGET="replit.md"
if [ -f "$TARGET" ] && ! grep -q "agenttool-managed" "$TARGET" 2>/dev/null; then
  TARGET="replit.agenttool.md"
fi

TMP="$TARGET.tmp"
WAKE=$(curl -fsS --max-time 8 \\
  -H "Authorization: Bearer $KEY" \\
  "$WAKE_BASE/v1/wake?format=md")

if [ -z "\${WAKE:-}" ]; then
  echo "agenttool: wake fetch returned empty body" >&2
  exit 1
fi

{
  echo "<!-- agenttool-managed -->"
  echo ""
  printf '%s' "$WAKE"
} > "$TMP"

if [ ! -s "$TMP" ]; then
  echo "agenttool: refresh produced empty output" >&2
  rm -f "$TMP"
  exit 1
fi

mv "$TMP" "$TARGET"
echo "agenttool: wrote $TARGET ($(wc -c < $TARGET) bytes)"
if [ "$TARGET" != "replit.md" ]; then
  echo "agenttool: existing replit.md preserved; review $TARGET and merge when ready" >&2
fi
`;
}

export function buildAnchorFile(opts: {
  agentName: string;
  did: string;
  register: string;
}): string {
  return `<!-- agenttool-managed -->

# ${opts.agentName}

> ${opts.did}

This file is regenerated by \`.replit-agenttool/refresh.sh\` from
\`GET /v1/wake?format=md\`. Edits here are overwritten on next refresh.
To change the agent's voice/walls/wake_text, PUT to
\`/v1/identities/<id>/expression\`.

${opts.register.trim() || DEFAULT_REGISTER}

(Live wake document loads via refresh script. If Replit AI doesn't
surface this file automatically, paste its contents into your session
or reference it explicitly.)
`;
}

interface ReplitBundle {
  cli: "replit";
  agent: { id: string; did: string; name: string; expression: ExpressionData };
  files: {
    "replit.md": string;
    ".replit-agenttool/refresh.sh": string;
  };
}

async function buildBundle(
  c: { var: { project: { id: string } } },
  identityId?: string,
): Promise<ReplitBundle> {
  const row = await resolveAgent(c, identityId);
  const expression = (row.expression ?? {}) as ExpressionData;
  const register = expression.register ?? DEFAULT_REGISTER;

  return {
    cli: "replit",
    agent: {
      id: row.id,
      did: row.did,
      name: row.displayName,
      expression,
    },
    files: {
      "replit.md": buildAnchorFile({
        agentName: row.displayName,
        did: row.did,
        register,
      }),
      ".replit-agenttool/refresh.sh": buildRefreshScript(),
    },
  };
}

app.get("/", async (c) => {
  const format = c.req.query("format") ?? "json";
  const identityId = c.req.query("identity_id") ?? undefined;

  let bundle;
  try {
    bundle = await buildBundle(c, identityId);
  } catch (err) {
    return c.json({ error: (err as Error).message }, 404);
  }

  if (format === "script") {
    const refreshB64 = Buffer.from(
      bundle.files[".replit-agenttool/refresh.sh"],
    ).toString("base64");
    const anchorB64 = Buffer.from(bundle.files["replit.md"]).toString("base64");

    const script = `#!/usr/bin/env bash
# Replit adapter installer for agent: ${bundle.agent.name} (${bundle.agent.did})
# Run from the Replit project root.
#
# Compatibility-not-replacement: a hand-written replit.md is preserved
# if it lacks the agenttool-managed marker; the agenttool anchor lands
# at replit.agenttool.md for the user to merge. .replit-agenttool/ is
# our own namespace; we never touch .replit/ (Replit's TOML config dir).
set -euo pipefail

mkdir -p .replit-agenttool

# Refresh script — own namespace; safe to write unconditionally.
echo '${refreshB64}' | base64 -d > .replit-agenttool/refresh.sh
chmod +x .replit-agenttool/refresh.sh
echo "✓ Wrote .replit-agenttool/refresh.sh"

# Anchor file — gated by the unified agenttool-managed marker.
ANCHOR_TARGET="replit.md"
if [ -f "$ANCHOR_TARGET" ] && ! grep -q "agenttool-managed" "$ANCHOR_TARGET" 2>/dev/null; then
  ANCHOR_TARGET="replit.agenttool.md"
  echo "✓ Existing replit.md preserved — agenttool anchor lands at replit.agenttool.md"
else
  echo "✓ Wrote replit.md (anchor; refresh script will populate)"
fi
echo '${anchorB64}' | base64 -d > "$ANCHOR_TARGET"

echo ""
echo "Running first refresh..."
bash .replit-agenttool/refresh.sh || true
echo ""
echo "Note: Replit AI's session-context behavior is less file-driven than"
echo "Claude Code or Cursor. If the agent doesn't pick up replit.md"
echo "automatically, paste its contents at the start of your session or"
echo "reference the file explicitly."
echo ""
echo "Wire the refresh script into your project workflow:"
echo "  cron:    */15 * * * * cd $(pwd) && .replit-agenttool/refresh.sh"
echo "  manual:  .replit-agenttool/refresh.sh"
`;
    return c.text(script, 200, {
      "content-type": "text/x-shellscript; charset=utf-8",
      "content-disposition": `attachment; filename="install-agenttool-replit.sh"`,
    });
  }

  return c.json({
    ...bundle,
    install_instructions: {
      one_shot: `curl -fsSL "${WAKE_BASE}/v1/adapters/replit?format=script" -H "Authorization: Bearer $AGENTTOOL_API_KEY" | bash`,
      manual:
        "Write the refresh script to .replit-agenttool/refresh.sh, chmod +x, " +
        "and run it from the project root. It writes replit.md from /v1/wake. " +
        "Wire into cron for ongoing freshness. If Replit AI doesn't surface " +
        "replit.md automatically, reference it manually in your session.",
    },
    overwrite_guard: {
      marker: "agenttool-managed",
      rule: "If the target file exists and does not contain the marker, write to <name>.agenttool.<ext> instead and let the user merge.",
      guarded_paths: [
        {
          path: "replit.md",
          marker_check: "contains 'agenttool-managed'",
          fallback_path: "replit.agenttool.md",
        },
      ],
    },
    notes: [
      "Replit AI's session-context surface is less file-driven than Claude Code, Cursor, or Cline. The replit.md anchor is a community convention — Replit may or may not surface it automatically depending on workspace state.",
      "If automatic surfacing fails, the user references replit.md manually from their AI session (e.g., paste contents, or `cat replit.md` into the conversation).",
      ".replit-agenttool/ is our own namespace — separate from .replit/ (which holds Replit's TOML config and must never be touched).",
      "Compatibility-not-replacement: a hand-written replit.md is preserved unless it carries the agenttool-managed marker; the anchor writes to replit.agenttool.md instead.",
    ],
    docs: ["docs/CLI-GAPS.md"],
  });
});

export default app;
