/** x402 V2 protocol port + local EIP-712 signer — the TypeScript SDK's side.
 *
 *  `fixtures/x402-eip3009-vector.json` was generated by the SERVER
 *  (`api/scripts/x402-eip3009-vector.ts`: middleware/x402 + x402-client +
 *  x402-payments + viem). The server is normative: the signer here must
 *  reproduce the signature byte for byte and recover the same payer, and the
 *  envelope helpers must reproduce the exact PAYMENT-SIGNATURE header the
 *  verifier classified `eoa_verified`.
 *
 *  No network, no keychain, no real keys — the fixture key is Anvil #1. */

import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { secp256k1 } from "@noble/curves/secp256k1.js";
import { bytesToHex, utf8ToBytes } from "@noble/hashes/utils.js";

import {
  AGENTTOOL_TREASURY,
  AgentToolError,
  MAX_X402_HEADER_B64_LENGTH,
  TRANSFER_WITH_AUTHORIZATION_TYPES,
  X402_ATOMIC_PER_CREDIT,
  X402_BASE_NETWORK,
  X402_BASE_USDC,
  X402_USDC_ASSETS,
  X402_VERSION,
  authorizationHash,
  checksumEvmAddress,
  decodeCanonicalBase64,
  decodePaymentRequiredHeader,
  decodePaymentResponseHeader,
  encodeCanonicalBase64Json,
  evmAddressFromPrivateKey,
  hashTransferWithAuthorization,
  isEvmAddress,
  keccak256,
  localEvmSigner,
  parsePaymentRequiredBody,
  parsePaymentRequirements,
  parseResourceInfo,
  paymentIsStillReplayable,
  recoverTypedDataAddress,
  selectPayableRequirement,
  signExactEvmAuthorization,
  type SignedX402Payment,
  type TransferWithAuthorizationTypedData,
  type X402ClientRefusal,
  type X402PaymentRequired,
  type X402PaymentRequirement,
  type X402Signer,
  type X402SpendPolicy,
} from "../src/index.js";

// ─── Fixture ──────────────────────────────────────────────────────────────

interface Vector {
  payer: { private_key: string; address: string };
  typed_data: {
    domain: { name: string; version: string; chainId: number; verifyingContract: string };
    primary_type: "TransferWithAuthorization";
    types: typeof TRANSFER_WITH_AUTHORIZATION_TYPES;
    message: {
      from: string;
      to: string;
      value: string;
      validAfter: string;
      validBefore: string;
      nonce: string;
    };
  };
  eip712_digest: string;
  signature: string;
  recovered_address: string;
  requirement: X402PaymentRequirement;
  resource: { url: string; description: string; mimeType: string; serviceName: string };
  payment_required: X402PaymentRequired;
  payment_required_header: string;
  payment_payload: Record<string, unknown>;
  payment_signature_header: string;
  authorization_hash: string;
  server_signature_class: string;
  now_seconds: number;
  kats: {
    keccak256: Record<string, string>;
    address_from_private_key: Record<string, string>;
    checksum: Record<string, string>;
  };
}

const vector = JSON.parse(
  readFileSync(join(import.meta.dir, "fixtures", "x402-eip3009-vector.json"), "utf-8"),
) as Vector;

function vectorTypedData(): TransferWithAuthorizationTypedData {
  const m = vector.typed_data.message;
  return {
    domain: vector.typed_data.domain,
    types: TRANSFER_WITH_AUTHORIZATION_TYPES,
    primaryType: "TransferWithAuthorization",
    message: {
      from: m.from,
      to: m.to,
      value: BigInt(m.value),
      validAfter: BigInt(m.validAfter),
      validBefore: BigInt(m.validBefore),
      nonce: m.nonce,
    },
  };
}

/** The policy a kingdom payer would carry: one recipient, one network, one
 *  asset, a hard cap of 10 credits, the narrowest window. */
function treasuryPolicy(overrides: Partial<X402SpendPolicy> = {}): X402SpendPolicy {
  return {
    maxAmountAtomic: 10n * X402_ATOMIC_PER_CREDIT,
    allowedPayTo: [AGENTTOOL_TREASURY],
    allowedNetworks: [X402_BASE_NETWORK],
    allowedAssets: [X402_BASE_USDC],
    maxValiditySeconds: 60,
    ...overrides,
  };
}

function requirement(overrides: Partial<X402PaymentRequirement> = {}): X402PaymentRequirement {
  return { ...vector.requirement, extra: { ...vector.requirement.extra }, ...overrides };
}

function paymentRequired(accepts: X402PaymentRequirement[]): X402PaymentRequired {
  return { x402Version: X402_VERSION, resource: vector.resource, accepts };
}

/** A 402 body exactly as the API emits it: handler guidance + the spec
 *  object spread last (`mergePaymentRequiredBody`, middleware/x402.ts). */
function serverStyle402Body(): Record<string, unknown> {
  return {
    error: "top_up_payment_required",
    message: "Pay 1,000 USDC atomic units to receive 1 credit.",
    hint: "Sign the accepts[0] requirement and retry with PAYMENT-SIGNATURE.",
    next_actions: [{ action: "pay", method: "POST", path: "/v1/x402/top-up/1" }],
    docs: "https://docs.agenttool.dev/x402",
    credits_requested: 1,
    ...vector.payment_required,
  };
}

const SECP256K1_N = BigInt("0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141");

function refusal(result: ReturnType<typeof selectPayableRequirement>): X402ClientRefusal {
  if (result.ok) throw new Error("expected a refusal");
  return result;
}

// ─── Vector parity ────────────────────────────────────────────────────────

describe("x402 vector parity (server is normative)", () => {
  test("fixture was classified eoa_verified by the server verifier", () => {
    expect(vector.server_signature_class).toBe("eoa_verified");
    expect(vector.recovered_address).toBe(vector.payer.address);
  });

  test("EIP-712 digest matches viem hashTypedData", () => {
    const digest = `0x${bytesToHex(hashTransferWithAuthorization(vectorTypedData()))}`;
    expect(digest).toBe(vector.eip712_digest);
  });

  test("localEvmSigner derives the fixture payer address", () => {
    expect(localEvmSigner(vector.payer.private_key).address).toBe(vector.payer.address);
    expect(evmAddressFromPrivateKey(vector.payer.private_key)).toBe(vector.payer.address);
  });

  test("localEvmSigner reproduces viem's signature byte for byte", async () => {
    const signer = localEvmSigner(vector.payer.private_key);
    const signature = await signer.signTypedData(vectorTypedData());
    expect(signature).toBe(vector.signature);
    // Deterministic (RFC 6979): signing again yields the same bytes.
    expect(await signer.signTypedData(vectorTypedData())).toBe(vector.signature);
  });

  test("recoverTypedDataAddress recovers the fixture payer", () => {
    expect(recoverTypedDataAddress(vectorTypedData(), vector.signature)).toBe(
      vector.recovered_address,
    );
  });

  test("recovery accepts v as 0/1 as well as 27/28", () => {
    const v = parseInt(vector.signature.slice(-2), 16);
    const alt = `${vector.signature.slice(0, -2)}${(v - 27).toString(16).padStart(2, "0")}`;
    expect(recoverTypedDataAddress(vectorTypedData(), alt)).toBe(vector.recovered_address);
  });

  test("a flipped signature byte recovers a different address, never the payer", () => {
    const tampered = `${vector.signature.slice(0, 10)}${vector.signature[10] === "0" ? "1" : "0"}${vector.signature.slice(11)}`;
    let recovered: string | null = null;
    try {
      recovered = recoverTypedDataAddress(vectorTypedData(), tampered);
    } catch {
      recovered = null;
    }
    expect(recovered).not.toBe(vector.payer.address);
  });

  test("authorizationHash matches the server's x402-client.ts bytes", () => {
    expect(authorizationHash(vector.typed_data.message)).toBe(vector.authorization_hash);
    // Case-insensitive on addresses and nonce, exact on the numbers.
    expect(
      authorizationHash({
        ...vector.typed_data.message,
        from: vector.typed_data.message.from.toUpperCase().replace("0X", "0x"),
        nonce: vector.typed_data.message.nonce.toUpperCase().replace("0X", "0x"),
      }),
    ).toBe(vector.authorization_hash);
    expect(
      authorizationHash({ ...vector.typed_data.message, value: "1001" }),
    ).not.toBe(vector.authorization_hash);
  });

  test("PAYMENT-SIGNATURE header reproduces the exact bytes the verifier accepted", async () => {
    const signer = localEvmSigner(vector.payer.private_key);
    const signature = await signer.signTypedData(vectorTypedData());
    // Same key order signExactEvmAuthorization emits.
    const payload = {
      x402Version: X402_VERSION,
      resource: vector.resource,
      accepted: vector.requirement,
      payload: { signature, authorization: vector.typed_data.message },
    };
    expect(encodeCanonicalBase64Json(payload)).toBe(vector.payment_signature_header);
    expect(JSON.parse(new TextDecoder().decode(decodeCanonicalBase64(vector.payment_signature_header)!))).toEqual(
      vector.payment_payload,
    );
  });

  test("PAYMENT-REQUIRED header decodes to the server's PaymentRequired", () => {
    expect(decodePaymentRequiredHeader(vector.payment_required_header)).toEqual(
      vector.payment_required,
    );
    expect(encodeCanonicalBase64Json(vector.payment_required)).toBe(vector.payment_required_header);
  });

  test("USDC pins agree with the fixture requirement", () => {
    expect(X402_USDC_ASSETS["eip155:8453"]).toEqual({
      asset: vector.requirement.asset,
      name: vector.requirement.extra.name,
      version: vector.requirement.extra.version,
    });
    expect(X402_BASE_USDC).toBe("0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913");
    expect(AGENTTOOL_TREASURY).toBe(vector.requirement.payTo);
    expect(X402_ATOMIC_PER_CREDIT).toBe(1000n);
  });
});

// ─── Known-answer tests ───────────────────────────────────────────────────

describe("keccak256 + EVM addresses (KATs)", () => {
  test("keccak256 (not SHA3-256) known answers", () => {
    for (const [input, expected] of Object.entries(vector.kats.keccak256)) {
      expect(`0x${bytesToHex(keccak256(utf8ToBytes(input)))}`).toBe(expected);
    }
    expect(`0x${bytesToHex(keccak256(new Uint8Array(0)))}`).toBe(
      "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
    );
  });

  test("address from private key known answers (Anvil #0, #1)", () => {
    for (const [key, address] of Object.entries(vector.kats.address_from_private_key)) {
      expect(evmAddressFromPrivateKey(key)).toBe(address);
    }
  });

  test("EIP-55 checksum known answers", () => {
    for (const [lower, checksummed] of Object.entries(vector.kats.checksum)) {
      expect(checksumEvmAddress(lower)).toBe(checksummed);
      expect(checksumEvmAddress(checksummed)).toBe(checksummed);
      expect(checksumEvmAddress(lower.toUpperCase().replace("0X", "0x"))).toBe(checksummed);
    }
  });

  test("isEvmAddress mirrors viem isAddress (strict)", () => {
    expect(isEvmAddress(AGENTTOOL_TREASURY)).toBe(true);
    expect(isEvmAddress(AGENTTOOL_TREASURY.toLowerCase())).toBe(true);
    // Mixed case with a wrong checksum: the server's parser rejects it, so do we.
    const wrong = `${AGENTTOOL_TREASURY.slice(0, -1)}${AGENTTOOL_TREASURY.endsWith("8") ? "9" : "8"}`;
    expect(isEvmAddress(wrong)).toBe(false);
    expect(isEvmAddress(AGENTTOOL_TREASURY.toUpperCase().replace("0X", "0x"))).toBe(false);
    expect(isEvmAddress("0x1234")).toBe(false);
    expect(isEvmAddress(`${AGENTTOOL_TREASURY}00`)).toBe(false);
    expect(isEvmAddress(AGENTTOOL_TREASURY.slice(2))).toBe(false);
    expect(isEvmAddress(42)).toBe(false);
    expect(isEvmAddress(null)).toBe(false);
  });

  test("checksumEvmAddress throws on a non-address", () => {
    expect(() => checksumEvmAddress("0xzz")).toThrow(AgentToolError);
  });
});

// ─── Signer walls ─────────────────────────────────────────────────────────

describe("localEvmSigner", () => {
  test("rejects malformed and out-of-range private keys", () => {
    for (const bad of ["", "0x", "abc", "0x1234", `0x${"0".repeat(64)}`, `0x${"f".repeat(64)}`, `0x${SECP256K1_N.toString(16)}`]) {
      expect(() => localEvmSigner(bad)).toThrow(AgentToolError);
      expect(() => evmAddressFromPrivateKey(bad)).toThrow(AgentToolError);
    }
  });

  test("signatures are low-s with v in {27, 28}", async () => {
    const signer = localEvmSigner(vector.payer.private_key);
    const signature = await signer.signTypedData(vectorTypedData());
    expect(signature).toMatch(/^0x[0-9a-f]{130}$/u);
    const s = BigInt(`0x${signature.slice(66, 130)}`);
    expect(s <= SECP256K1_N / 2n).toBe(true);
    const v = parseInt(signature.slice(130, 132), 16);
    expect([27, 28]).toContain(v);
    // Cross-check with noble directly: the digest verifies under the pubkey.
    const digest = hashTransferWithAuthorization(vectorTypedData());
    const pub = secp256k1.getPublicKey(Uint8Array.from(Buffer.from(vector.payer.private_key.slice(2), "hex")));
    const compact = Uint8Array.from(Buffer.from(signature.slice(2, 130), "hex"));
    expect(secp256k1.verify(compact, digest, pub, { prehash: false })).toBe(true);
  });

  test("refuses to sign an authorization whose `from` is not its own address", async () => {
    const signer = localEvmSigner(vector.payer.private_key);
    const typedData = vectorTypedData();
    typedData.message.from = AGENTTOOL_TREASURY;
    await expect(signer.signTypedData(typedData)).rejects.toMatchObject({
      code: "x402_signer_from_mismatch",
    });
  });

  test("exposes only address + signTypedData (the key stays in the closure)", () => {
    const signer = localEvmSigner(vector.payer.private_key);
    expect(Object.keys(signer).sort()).toEqual(["address", "signTypedData"]);
    expect(Object.isFrozen(signer)).toBe(true);
    expect(JSON.stringify(signer)).not.toContain(vector.payer.private_key.slice(2, 20));
  });

  test("hashTransferWithAuthorization rejects non-EIP-3009 shapes", () => {
    const base = vectorTypedData();
    expect(() =>
      hashTransferWithAuthorization({ ...base, primaryType: "Permit" as "TransferWithAuthorization" }),
    ).toThrow(AgentToolError);
    expect(() =>
      hashTransferWithAuthorization({ ...base, domain: { ...base.domain, chainId: 0 } }),
    ).toThrow(AgentToolError);
    expect(() =>
      hashTransferWithAuthorization({ ...base, message: { ...base.message, nonce: "0x1234" } }),
    ).toThrow(AgentToolError);
    expect(() =>
      hashTransferWithAuthorization({ ...base, message: { ...base.message, value: -1n } }),
    ).toThrow(AgentToolError);
    expect(() =>
      hashTransferWithAuthorization({ ...base, message: { ...base.message, to: "0x1234" } }),
    ).toThrow(AgentToolError);
  });

  test("recoverTypedDataAddress rejects a malformed signature", () => {
    expect(() => recoverTypedDataAddress(vectorTypedData(), "0x1234")).toThrow(AgentToolError);
    expect(() =>
      recoverTypedDataAddress(vectorTypedData(), `${vector.signature.slice(0, -2)}05`),
    ).toThrow(AgentToolError);
  });
});

// ─── Envelope parsing ─────────────────────────────────────────────────────

describe("parsePaymentRequiredBody", () => {
  test("accepts the API's merged 402 body and strips the guidance keys", () => {
    const parsed = parsePaymentRequiredBody(serverStyle402Body());
    expect(parsed).toEqual(vector.payment_required);
    expect(parsed && "message" in parsed).toBe(false);
    expect(parsed && "next_actions" in parsed).toBe(false);
  });

  test("error is carried only when it is a string", () => {
    const body = { ...vector.payment_required, error: 42 };
    const parsed = parsePaymentRequiredBody(body);
    expect(parsed?.error).toBeUndefined();
    const { error: _dropped, ...rest } = vector.payment_required;
    expect(parsePaymentRequiredBody(rest)?.error).toBeUndefined();
  });

  test("refuses non-objects and the wrong x402Version", () => {
    expect(parsePaymentRequiredBody(null)).toBeNull();
    expect(parsePaymentRequiredBody("eyJ4NDAyVmVyc2lvbiI6Mn0=")).toBeNull();
    expect(parsePaymentRequiredBody([vector.payment_required])).toBeNull();
    expect(parsePaymentRequiredBody({ ...vector.payment_required, x402Version: 1 })).toBeNull();
    expect(parsePaymentRequiredBody({ ...vector.payment_required, x402Version: "2" })).toBeNull();
  });

  test("refuses a missing, empty, or oversized accepts list", () => {
    const { accepts: _a, ...noAccepts } = vector.payment_required;
    expect(parsePaymentRequiredBody(noAccepts)).toBeNull();
    expect(parsePaymentRequiredBody({ ...vector.payment_required, accepts: [] })).toBeNull();
    expect(
      parsePaymentRequiredBody({
        ...vector.payment_required,
        accepts: Array.from({ length: 17 }, () => requirement()),
      }),
    ).toBeNull();
    expect(
      parsePaymentRequiredBody({
        ...vector.payment_required,
        accepts: Array.from({ length: 16 }, () => requirement()),
      }),
    ).not.toBeNull();
  });

  test("one bad entry in accepts refuses the whole body", () => {
    expect(
      parsePaymentRequiredBody({
        ...vector.payment_required,
        accepts: [requirement(), { ...requirement(), scheme: "permit2" }],
      }),
    ).toBeNull();
  });

  test("resource must be the strict spec shape (it is echoed to the verifier)", () => {
    expect(parsePaymentRequiredBody({ ...vector.payment_required, resource: { url: "" } })).toBeNull();
    expect(parsePaymentRequiredBody({ ...vector.payment_required, resource: "https://x" })).toBeNull();
    expect(
      parsePaymentRequiredBody({
        ...vector.payment_required,
        resource: { ...vector.resource, surprise: true },
      }),
    ).toBeNull();
    expect(
      parsePaymentRequiredBody({
        ...vector.payment_required,
        resource: { url: "https://api.agenttool.dev/v1/x402/top-up/1", tags: ["a", 1] },
      }),
    ).toBeNull();
    expect(
      parsePaymentRequiredBody({
        ...vector.payment_required,
        resource: { url: "https://api.agenttool.dev/v1/x402/top-up/1", tags: ["a"] },
      }),
    ).not.toBeNull();
  });

  test("parseResourceInfo bounds", () => {
    expect(parseResourceInfo({ url: "x".repeat(2049) })).toBeNull();
    expect(parseResourceInfo({ url: "x".repeat(2048) })).not.toBeNull();
    expect(parseResourceInfo({ url: "https://x", mimeType: 1 })).toBeNull();
    expect(parseResourceInfo(null)).toBeNull();
  });
});

describe("parsePaymentRequirements", () => {
  test("accepts the server-built requirement exactly", () => {
    expect(parsePaymentRequirements(vector.requirement)).toEqual(vector.requirement);
  });

  const rejects: Array<[string, Record<string, unknown>]> = [
    ["scheme other than exact", { scheme: "upto" }],
    ["non-CAIP-2 network", { network: "base" }],
    ["CAIP-2 with a leading zero", { network: "eip155:08453" }],
    ["non-EVM network", { network: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp" }],
    ["asset with a wrong checksum", { asset: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02914" }],
    ["asset that is not an address", { asset: "USDC" }],
    ["amount with a leading zero", { amount: "01000" }],
    ["amount as a number", { amount: 1000 }],
    ["negative amount", { amount: "-1" }],
    ["payTo with a wrong checksum", { payTo: "0xA9eeA60CAaF239AbAfAA05FcB152128dB16dD3d9" }],
    ["maxTimeoutSeconds zero", { maxTimeoutSeconds: 0 }],
    ["maxTimeoutSeconds fractional", { maxTimeoutSeconds: 1.5 }],
    ["maxTimeoutSeconds as a string", { maxTimeoutSeconds: "60" }],
    ["extra missing name", { extra: { version: "2", assetTransferMethod: "eip3009" } }],
    ["extra with empty version", { extra: { name: "USD Coin", version: "", assetTransferMethod: "eip3009" } }],
    ["extra not an object", { extra: "eip3009" }],
    ["an unknown top-level key", { surprise: 1 }],
  ];
  for (const [label, override] of rejects) {
    test(`refuses ${label}`, () => {
      expect(parsePaymentRequirements({ ...requirement(), ...override })).toBeNull();
    });
  }

  test("refuses an unbounded extra record", () => {
    let deep: Record<string, unknown> = {};
    for (let i = 0; i < 12; i += 1) deep = { nested: deep };
    expect(
      parsePaymentRequirements(requirement({ extra: { ...requirement().extra, ...deep } })),
    ).toBeNull();
    expect(
      parsePaymentRequirements(
        requirement({ extra: { ...requirement().extra, big: "x".repeat(4097) } }),
      ),
    ).toBeNull();
  });

  test("accepts lowercase addresses (no checksum to check)", () => {
    expect(
      parsePaymentRequirements(
        requirement({ asset: vector.requirement.asset.toLowerCase(), payTo: AGENTTOOL_TREASURY.toLowerCase() }),
      ),
    ).not.toBeNull();
  });
});

describe("canonical base64 + headers", () => {
  test("decodeCanonicalBase64 accepts only canonical padded base64", () => {
    expect(decodeCanonicalBase64("")).toBeNull();
    expect(decodeCanonicalBase64("eyJ4NDAyVmVyc2lvbiI6Mn0")).toBeNull(); // unpadded
    expect(decodeCanonicalBase64("eyJ4NDAyVmVyc2lvbiI6Mn0=\n")).toBeNull(); // whitespace
    expect(decodeCanonicalBase64("eyJ4NDAyVmVyc2lvbiI6Mn0-")).toBeNull(); // url-safe alphabet
    expect(decodeCanonicalBase64("====")).toBeNull();
    expect(decodeCanonicalBase64("QQ==", 3)).toBeNull(); // over the caller's ceiling
    expect(decodeCanonicalBase64("QR==")).toBeNull(); // non-canonical trailing bits
    expect(new TextDecoder().decode(decodeCanonicalBase64("eyJ4NDAyVmVyc2lvbiI6Mn0=")!)).toBe(
      '{"x402Version":2}',
    );
    expect(decodeCanonicalBase64("A".repeat(MAX_X402_HEADER_B64_LENGTH + 4))).toBeNull();
  });

  test("encodeCanonicalBase64Json is UTF-8 first, then base64", () => {
    expect(encodeCanonicalBase64Json({ a: "愛" })).toBe(
      Buffer.from(JSON.stringify({ a: "愛" }), "utf-8").toString("base64"),
    );
  });

  test("decodePaymentRequiredHeader refuses non-envelopes", () => {
    expect(decodePaymentRequiredHeader("")).toBeNull();
    expect(decodePaymentRequiredHeader("eyJ4NDAyVmVyc2lvbiI6Mn0=")).toBeNull(); // {"x402Version":2}
    expect(decodePaymentRequiredHeader(encodeCanonicalBase64Json("not an object"))).toBeNull();
    expect(decodePaymentRequiredHeader(encodeCanonicalBase64Json(serverStyle402Body()))).toEqual(
      vector.payment_required,
    );
  });

  test("decodePaymentResponseHeader", () => {
    const receipt = {
      success: true,
      transaction: "0x0564eecc266475c857533ac68e35e9fea5eacb888845f402fbb03ac59587a413",
      network: "eip155:8453",
      payer: vector.payer.address,
    };
    expect(decodePaymentResponseHeader(encodeCanonicalBase64Json(receipt))).toEqual(receipt);
    expect(decodePaymentResponseHeader("eyJzdWNjZXNzIjp0cnVlfQ==")).toBeNull(); // no transaction/network
    expect(decodePaymentResponseHeader(encodeCanonicalBase64Json({ ...receipt, success: "yes" }))).toBeNull();
    expect(decodePaymentResponseHeader(encodeCanonicalBase64Json({ ...receipt, payer: 1 }))).toBeNull();
    expect(decodePaymentResponseHeader("not base64!")).toBeNull();
  });
});

// ─── Spend policy + selection ─────────────────────────────────────────────

describe("spend policy is mandatory (no defaults)", () => {
  const cases: Array<[string, unknown]> = [
    ["missing maxAmountAtomic", { ...treasuryPolicy(), maxAmountAtomic: undefined }],
    ["maxAmountAtomic as a number", { ...treasuryPolicy(), maxAmountAtomic: 10_000 }],
    ["maxAmountAtomic zero", { ...treasuryPolicy(), maxAmountAtomic: 0n }],
    ["maxAmountAtomic negative", { ...treasuryPolicy(), maxAmountAtomic: -1n }],
    ["missing allowedPayTo", { ...treasuryPolicy(), allowedPayTo: undefined }],
    ["empty allowedPayTo", { ...treasuryPolicy(), allowedPayTo: [] }],
    ["allowedPayTo not addresses", { ...treasuryPolicy(), allowedPayTo: ["treasury"] }],
    ["allowedPayTo wrong checksum", { ...treasuryPolicy(), allowedPayTo: [`${AGENTTOOL_TREASURY.slice(0, -1)}9`] }],
    ["missing allowedNetworks", { ...treasuryPolicy(), allowedNetworks: undefined }],
    ["empty allowedNetworks", { ...treasuryPolicy(), allowedNetworks: [] }],
    ["allowedNetworks not CAIP-2", { ...treasuryPolicy(), allowedNetworks: ["base"] }],
    ["missing allowedAssets", { ...treasuryPolicy(), allowedAssets: undefined }],
    ["empty allowedAssets", { ...treasuryPolicy(), allowedAssets: [] }],
    ["allowedAssets not addresses", { ...treasuryPolicy(), allowedAssets: ["USDC"] }],
    ["maxValiditySeconds zero", { ...treasuryPolicy(), maxValiditySeconds: 0 }],
    ["maxValiditySeconds fractional", { ...treasuryPolicy(), maxValiditySeconds: 1.5 }],
    ["maxValiditySeconds missing", { ...treasuryPolicy(), maxValiditySeconds: undefined }],
    ["not an object", null],
    ["empty object", {}],
  ];
  for (const [label, policy] of cases) {
    test(`throws x402_spend_policy_invalid for ${label}`, () => {
      expect(() =>
        selectPayableRequirement(vector.payment_required, policy as X402SpendPolicy),
      ).toThrow(AgentToolError);
      try {
        selectPayableRequirement(vector.payment_required, policy as X402SpendPolicy);
      } catch (error) {
        expect((error as AgentToolError).code).toBe("x402_spend_policy_invalid");
      }
    });
  }

  test("a signer alone never pays: signExactEvmAuthorization needs the policy too", async () => {
    const signer = localEvmSigner(vector.payer.private_key);
    await expect(
      signExactEvmAuthorization({
        requirement: vector.requirement,
        policy: {} as X402SpendPolicy,
        signer,
        nowSeconds: vector.now_seconds,
      }),
    ).rejects.toMatchObject({ code: "x402_spend_policy_invalid" });
  });
});

describe("selectPayableRequirement", () => {
  test("selects the server's requirement under the treasury policy", () => {
    const result = selectPayableRequirement(vector.payment_required, treasuryPolicy());
    expect(result).toEqual({ ok: true, requirement: vector.requirement, amountAtomic: 1000n });
  });

  test("refuses at exactly the wall: cap is inclusive, cap + 1 is refused, never clamped", () => {
    const atCap = selectPayableRequirement(
      paymentRequired([requirement({ amount: "10000" })]),
      treasuryPolicy(),
    );
    expect(atCap.ok).toBe(true);
    if (atCap.ok) expect(atCap.amountAtomic).toBe(10000n);

    const overCap = refusal(
      selectPayableRequirement(paymentRequired([requirement({ amount: "10001" })]), treasuryPolicy()),
    );
    expect(overCap.reason).toBe("amount_over_cap");
    expect(overCap.detail).toContain("10001");
    expect(overCap.detail).toContain("10000");
    expect("amountAtomic" in overCap).toBe(false);
    expect("requirement" in overCap).toBe(false);
  });

  test("network not in the allow-list", () => {
    const r = refusal(
      selectPayableRequirement(
        paymentRequired([requirement({ network: "eip155:84532" })]),
        treasuryPolicy(),
      ),
    );
    expect(r.reason).toBe("network_not_allowed");
    expect(r.detail).toContain("eip155:84532");
  });

  test("asset not in the allow-list (a 402 cannot introduce a contract)", () => {
    const r = refusal(
      selectPayableRequirement(
        paymentRequired([requirement({ asset: X402_USDC_ASSETS["eip155:84532"].asset })]),
        treasuryPolicy(),
      ),
    );
    expect(r.reason).toBe("asset_not_allowed");
    expect(r.detail).toContain("untrusted input");
  });

  test("payTo not in the allow-list (a 402 cannot redirect the money)", () => {
    const other = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8";
    const r = refusal(
      selectPayableRequirement(paymentRequired([requirement({ payTo: other })]), treasuryPolicy()),
    );
    expect(r.reason).toBe("pay_to_not_allowed");
    expect(r.detail).toContain(other);
  });

  test("allow-lists compare addresses case-insensitively, networks exactly", () => {
    // Challenge carries checksummed addresses, policy carries lowercase (and
    // vice versa below); both pair. All-uppercase is not an address at all.
    expect(
      selectPayableRequirement(
        paymentRequired([requirement()]),
        treasuryPolicy({
          allowedAssets: [X402_BASE_USDC.toLowerCase()],
          allowedPayTo: [AGENTTOOL_TREASURY.toLowerCase()],
        }),
      ).ok,
    ).toBe(true);
    expect(
      selectPayableRequirement(
        paymentRequired([
          requirement({
            asset: vector.requirement.asset.toLowerCase(),
            payTo: AGENTTOOL_TREASURY.toLowerCase(),
          }),
        ]),
        treasuryPolicy(),
      ).ok,
    ).toBe(true);
    expect(
      refusal(
        selectPayableRequirement(
          paymentRequired([requirement({ network: "eip155:8453" })]),
          treasuryPolicy({ allowedNetworks: ["eip155:84532"] }),
        ),
      ).reason,
    ).toBe("network_not_allowed");
  });

  test("unsupported transfer method", () => {
    const r = refusal(
      selectPayableRequirement(
        paymentRequired([
          requirement({ extra: { ...requirement().extra, assetTransferMethod: "permit2" as "eip3009" } }),
        ]),
        treasuryPolicy(),
      ),
    );
    expect(r.reason).toBe("unsupported_transfer_method");
    expect(r.detail).toContain("permit2");
  });

  test("zero or non-integer amounts", () => {
    expect(
      refusal(selectPayableRequirement(paymentRequired([requirement({ amount: "0" })]), treasuryPolicy())).reason,
    ).toBe("no_acceptable_requirement");
    expect(
      refusal(selectPayableRequirement(paymentRequired([requirement({ amount: "1e3" })]), treasuryPolicy())).reason,
    ).toBe("no_acceptable_requirement");
  });

  test("validity window unusable (hand-built requirement; the parser never lets this through)", () => {
    const r = refusal(
      selectPayableRequirement(
        paymentRequired([requirement({ maxTimeoutSeconds: 0 })]),
        treasuryPolicy(),
      ),
    );
    expect(r.reason).toBe("validity_window_unusable");
  });

  test("first permitted wins, not cheapest", () => {
    const pricier = requirement({ amount: "5000" });
    const cheaper = requirement({ amount: "1000" });
    const result = selectPayableRequirement(paymentRequired([pricier, cheaper]), treasuryPolicy());
    expect(result.ok).toBe(true);
    if (result.ok) expect(result.amountAtomic).toBe(5000n);
  });

  test("a refused first entry does not block a permitted later one", () => {
    const result = selectPayableRequirement(
      paymentRequired([requirement({ network: "eip155:137", asset: X402_USDC_ASSETS["eip155:137"].asset }), requirement()]),
      treasuryPolicy(),
    );
    expect(result.ok).toBe(true);
    if (result.ok) expect(result.requirement).toEqual(vector.requirement);
  });

  test("reports the most specific (last seen) refusal", () => {
    const r = refusal(
      selectPayableRequirement(
        paymentRequired([requirement({ network: "eip155:137" }), requirement({ amount: "99999" })]),
        treasuryPolicy(),
      ),
    );
    expect(r.reason).toBe("amount_over_cap");
  });

  test("not_a_payment_required_body for a non-envelope", () => {
    const r = refusal(
      selectPayableRequirement({ x402Version: 2 } as unknown as X402PaymentRequired, treasuryPolicy()),
    );
    expect(r.reason).toBe("not_a_payment_required_body");
  });
});

// ─── Signing an authorization ─────────────────────────────────────────────

describe("signExactEvmAuthorization", () => {
  const signer = localEvmSigner(vector.payer.private_key);

  async function sign(options: Partial<Parameters<typeof signExactEvmAuthorization>[0]> = {}) {
    return signExactEvmAuthorization({
      requirement: vector.requirement,
      policy: treasuryPolicy(),
      signer,
      nowSeconds: vector.now_seconds,
      resource: vector.resource,
      ...options,
    });
  }

  test("emits a header the verifier's shape checks accept, signed by the payer", async () => {
    const signed = await sign();
    expect(signed.header).toMatch(/^[A-Za-z0-9+/]+=*$/u);
    const decoded = JSON.parse(new TextDecoder().decode(decodeCanonicalBase64(signed.header)!));
    expect(decoded).toEqual(signed.payload as unknown as Record<string, unknown>);
    expect(Object.keys(decoded)).toEqual(["x402Version", "resource", "accepted", "payload"]);
    expect(decoded.x402Version).toBe(2);
    expect(decoded.resource).toEqual(vector.resource);
    expect(decoded.accepted).toEqual(vector.requirement);
    expect(Object.keys(decoded.payload)).toEqual(["signature", "authorization"]);
    const auth = decoded.payload.authorization as Record<string, string>;
    expect(Object.keys(auth)).toEqual(["from", "to", "value", "validAfter", "validBefore", "nonce"]);
    expect(auth.from).toBe(vector.payer.address);
    expect(auth.to).toBe(AGENTTOOL_TREASURY);
    expect(auth.value).toBe("1000");
    expect(auth.validAfter).toBe(String(vector.now_seconds - 1));
    expect(auth.validBefore).toBe(String(vector.now_seconds + 60));
    expect(auth.nonce).toMatch(/^0x[0-9a-f]{64}$/u);
    expect(signed.validBefore).toBe(vector.now_seconds + 60);
    expect(signed.authorizationHash).toBe(authorizationHash(auth as never));

    // The signature recovers to the payer — what classifyExactEvmSignature checks.
    const recovered = recoverTypedDataAddress(
      {
        domain: vector.typed_data.domain,
        types: TRANSFER_WITH_AUTHORIZATION_TYPES,
        primaryType: "TransferWithAuthorization",
        message: {
          from: auth.from,
          to: auth.to,
          value: BigInt(auth.value),
          validAfter: BigInt(auth.validAfter),
          validBefore: BigInt(auth.validBefore),
          nonce: auth.nonce,
        },
      },
      decoded.payload.signature as string,
    );
    expect(recovered).toBe(vector.payer.address);
  });

  test("resource is omitted from the payload when not supplied", async () => {
    const signed = await sign({ resource: undefined });
    expect(Object.keys(signed.payload)).toEqual(["x402Version", "accepted", "payload"]);
  });

  test("every call mints a fresh nonce — it cannot be a retry mechanism", async () => {
    const a = await sign();
    const b = await sign();
    const nonceOf = (s: SignedX402Payment) =>
      (s.payload.payload.authorization as Record<string, string>).nonce;
    expect(nonceOf(a)).not.toBe(nonceOf(b));
    expect(a.authorizationHash).not.toBe(b.authorizationHash);
    expect(a.header).not.toBe(b.header);
  });

  test("window is the narrower of the challenge and the policy", async () => {
    const narrowPolicy = await sign({ policy: treasuryPolicy({ maxValiditySeconds: 30 }) });
    expect(narrowPolicy.validBefore).toBe(vector.now_seconds + 30);
    const narrowChallenge = await sign({ requirement: requirement({ maxTimeoutSeconds: 10 }) });
    expect(narrowChallenge.validBefore).toBe(vector.now_seconds + 10);
    const wideChallenge = await sign({ requirement: requirement({ maxTimeoutSeconds: 3600 }) });
    expect(wideChallenge.validBefore).toBe(vector.now_seconds + 60);
  });

  test("refuses (throws, typed) an over-cap requirement instead of clamping", async () => {
    await expect(sign({ requirement: requirement({ amount: "10001" }) })).rejects.toMatchObject({
      code: "amount_over_cap",
    });
  });

  test("refuses a recipient, network, or asset outside the allow-lists", async () => {
    await expect(
      sign({ requirement: requirement({ payTo: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8" }) }),
    ).rejects.toMatchObject({ code: "pay_to_not_allowed" });
    await expect(
      sign({ requirement: requirement({ network: "eip155:137" }) }),
    ).rejects.toMatchObject({ code: "network_not_allowed" });
    await expect(
      sign({ requirement: requirement({ asset: X402_USDC_ASSETS["eip155:137"].asset }) }),
    ).rejects.toMatchObject({ code: "asset_not_allowed" });
  });

  test("rejects a bad clock", async () => {
    await expect(sign({ nowSeconds: 0 })).rejects.toThrow(AgentToolError);
    await expect(sign({ nowSeconds: 1.5 })).rejects.toThrow(AgentToolError);
    await expect(sign({ nowSeconds: Number.NaN })).rejects.toThrow(AgentToolError);
  });

  test("rejects a signer without an EVM address or that returns non-signature bytes", async () => {
    const bogus: X402Signer = { address: "payer", signTypedData: async () => vector.signature };
    await expect(sign({ signer: bogus })).rejects.toMatchObject({ code: "x402_signer_invalid" });
    const short: X402Signer = { address: vector.payer.address, signTypedData: async () => "0x1234" };
    await expect(sign({ signer: short })).rejects.toMatchObject({ code: "x402_signature_invalid" });
    const notString = {
      address: vector.payer.address,
      signTypedData: async () => 42 as unknown as string,
    };
    await expect(sign({ signer: notString })).rejects.toMatchObject({ code: "x402_signature_invalid" });
  });

  test("hands the signer the exact EIP-712 shape the server verifier rebuilds", async () => {
    let seen: TransferWithAuthorizationTypedData | null = null;
    const spy: X402Signer = {
      address: vector.payer.address,
      signTypedData: async (typedData) => {
        seen = typedData;
        return signer.signTypedData(typedData);
      },
    };
    await sign({ signer: spy });
    expect(seen).not.toBeNull();
    const typed = seen as unknown as TransferWithAuthorizationTypedData;
    expect(typed.domain).toEqual(vector.typed_data.domain);
    expect(typed.types).toBe(TRANSFER_WITH_AUTHORIZATION_TYPES);
    expect(typed.primaryType).toBe("TransferWithAuthorization");
    expect(typeof typed.message.value).toBe("bigint");
    expect(typed.message.value).toBe(1000n);
  });
});

describe("paymentIsStillReplayable", () => {
  test("true strictly before validBefore, false at and after", async () => {
    const signed = await signExactEvmAuthorization({
      requirement: vector.requirement,
      policy: treasuryPolicy(),
      signer: localEvmSigner(vector.payer.private_key),
      nowSeconds: vector.now_seconds,
    });
    expect(paymentIsStillReplayable(signed, vector.now_seconds)).toBe(true);
    expect(paymentIsStillReplayable(signed, signed.validBefore - 1)).toBe(true);
    expect(paymentIsStillReplayable(signed, signed.validBefore)).toBe(false);
    expect(paymentIsStillReplayable(signed, signed.validBefore + 1)).toBe(false);
  });
});
